### ISSUE TITLE
Excalidraw support i.e. docs on producing svg and conversion

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#10]
## Acceptance

* [ ] Excalidraw images are published

BONUS (future for now probably)

* [ ] Excalidraw images that are transcluded show up as they should even if using the default notation (i.e. not svg or png transclude)

## Tasks

* [ ] Displaying excalidraw images
  * [ ] Instructions to users on how to configure excalidraw to auto generate svg files (or png files?)
  * [ ] copying them to the `public` folder
  * [ ] ~~Convert excalidraw embed codes to use the svg or png automatically?~~ (just use the support of obsidian plugin which does this for you - don't get fancy)
* [ ] Excalidraw excluded from contentlayer build (has .md files which aren't really md files) **May not be needed as seems to be working ok without it. YAGNI**
   * [ ] what happens if users are using a custom folder name? Let's default to `Excalidraw` at root of content folder

**Comment by khalilcodes** [comment]
@olayway 

* > copying them to the public folder

  can't we just drop the excalidraw folder into the assets folder and let users reference that ? eg. `assets/excalidraw/...`

* > Convert excalidraw embed codes to use the svg or png automatically?

  should this be a remark plugin ?

**Comment by rufuspollock** [comment]
@khalilcodes my sense is this is more about documentation (as per tasks):

- explaining how in obsidian you confirgure it to create svg and insert those rather than excalidraw links
- symlinking excalidraw folder into public

That's it for now ... 

(also updated acceptance to make one option a future item)

**Comment by khalilcodes** [comment]
@rufuspollock maybe for future ...

Excalidraw has a react package with which we can embed into our project - https://www.npmjs.com/package/@excalidraw/excalidraw

**Comment by rufuspollock** [comment]
@khalilcodes reviewing and need edit rights. Key points is really only 2 steps here:

0. (preliminary) we assume you are using the excalidraw plugin in obsidian
1. configure the plugin to export svg or png 
2. make sure you have a defined folder for your excalidraw files. symlink this directory into public folder in flowershow

<img width="791" alt="image" src="https://user-images.githubusercontent.com/180658/206430017-048a92d0-721c-4a28-88c1-e5cb80e01160.png">

Note that you can choose png or svg ...

<img width="794" alt="image" src="https://user-images.githubusercontent.com/180658/206430045-cd10786e-10dc-49ac-b508-67f7b9b704d6.png">
