### ISSUE TITLE
Design CLI install experience

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#114]
When i have markdown i want an easy way to use flowershow to create my site so that it is published

## Acceptance

* [x] Have plan of work re UX and implementation e.g. #19 **🚧2022-09-01 here https://flowershow.app/meta/install-design** **✅2022-10-27 this was done at least by the alpha release on Nov 7 2022 as we had full CLI https://flowershow.app/blog/alpha-release #134**

## Tasks

Preliminary

* [x] clarify the use cases people have e.g. publishing markdown files, making a nextjs website with a template (where they will modify the template) **✅2022-11-25 focused on pure publish (not use as nextjs template) for now**

Install

* [x] What is the outcome people want **✅2022-12-03 a working site (that they can self publish)**
  * [x] What is it people are publishing
  * [x] How should they lay it out for flowershow 
* [x] What is the concrete command line experience that looks like **✅2022-12-03 `npx flowershow install & npx flowershow build**
* [x] (vaguely) how would that be implemented
* [x] What implications does that have for modifying the experience

**Comment by rufuspollock** [comment]
FIXED.  a while ago e.g. this was done at least by the alpha release on Nov 7 2022 as we had full CLI - see https://flowershow.app/blog/alpha-release and #134
