### ISSUE TITLE
Smartypants support e.g. for ndash, mdash etc

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#118]
When writing markdown i want to use `--` and have it turn into ndash so that i can write elegantly

Suggest we can use https://github.com/silvenon/remark-smartypants

And then turn off quotes stuff and just have ellipsis and oldschool dash support.

## Acceptance

* [x] `--` becomes ndash
* [x] `---` becomes mdash
* [x] `...` becomes ellipse
* [x] Add a brief comment to `/docs/syntax` with a demo (which can also act as a test)
* [ ] (BONUS) add this to tests

## Tasks

* [x] Read up on https://github.com/silvenon/remark-smartypants
* [x] Add it to remark config in contentlayer.config.js
* [x] Add docs **[added](https://github.com/flowershow/flowershow/blob/main/site/content/docs/syntax.md#-dashesellipse)**

**Comment by bilalshaikh292** [comment]
@rufuspollock so can you explain me the work once?so that i can start working?

**Comment by rufuspollock** [comment]
@bilalshaikh292 can you have a look around https://flowershow.app and the codebase and familiarize yourself and see what questions you have. I will also add a bit more info here.

**Comment by olayway** [comment]
@PhilippeduPreez one more thing to do here is adding a section to docs showing how `smartypants` works :) Sth similar to: https://flowershow.app/docs/syntax#-emphasis

**Comment by rufuspollock** [comment]
@PhilippeduPreez can you please close as per https://tao.lifeitself.us/issues/

**Comment by PhilippeduPreez** [comment]
FIXED. See commit [here](https://github.com/flowershow/flowershow/pull/159/commits/512e2ce468e6f559c91be949ca73c2130502ceb3)
