### ISSUE TITLE
Step-by-step overview of raw self-publishing on front page

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#125]
Follow on to #103 to cover self-publishing. For steps see https://flowershow.app/meta/publishing-design section Self-publishing in the rawest way

1. You have a have some markdown files (and maybe data). Preferably in a git repo.
2. You install the flowershow app template (later this could be encapsulated in a command line tool)
3. You configure the app with your content in step 1
4. You deploy: self-service (to your static site hoster of choice) or cloud (using flowershow tooling)
5. [Share the result]

## Acceptance

* [x] Section like the cloud version on the front page (below the cloud one)
* [x] Disclaimer about not yet fully working and (e.g.) sign up if you want to try it out

Note this is about giving the flavour of it, does not have to be perfectly accurate (full docs will come later)

## Tasks

* [ ] Clarify the steps (are the ones above correct) e.g. do we start with files in a git repo (strictly you could self-publish without e.g. to s3)
* [ ] Implement
