### ISSUE TITLE
Private Notes that aren't published (Enable publishing only selected set of notes)

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#128]
When publishing my vault i want to be able to have an individual note not published so that i can keep work as draft

When publishing my vault i want to default to having all notes unpublished and notes are only published if explicitly marked so that i can only selectively publish and keep most of my vault private

When publishing my vault i want to be able to bulk configure notes as published (or not published) using the config so that I don't have to individually mark notes as published or not in their frontmatter

## Acceptance

- [x] ability to include/exclude specific files/directories **add any files/dir in contentExclude config that should not be published** 
- [x] ability to exclude individual notes using frontmatter field: `draft: true` **isDraft: true can be added in frontmatter in order not to be published, even if it is in a dir that is published**
- [x] feature documented in `docs/config` page **Still add isDraft fontmatter to docs**

## Notes

We could use e.g. glob patterns in `config.js` to include/exclude specific set of files.

**Comment by rufuspollock** [comment]
@olayway added some job stories

**Comment by PhilippeduPreez** [comment]
@olayway Glob/wildcard patterns (e.g. using *) are not supported yet for contentDirExclude or contentDirInclude. https://www.contentlayer.dev/docs/reference/source-files/make-source#contentdirinclude

We should be able to add specific folders/files in config that would be use in Contentlayer?

**Comment by PhilippeduPreez** [comment]
isDraft: true can be added in frontmatter in order not to be published. Since I am not sure if we are able to check the frontmatter in contentlayer.config, I added the check in getStaticPaths and sent a 404 if a page has this in frontmatter.

**Comment by PhilippeduPreez** [comment]
FIXED [here](https://github.com/flowershow/flowershow/pull/202/commits/225dab060f34687764cec057c0a67db657d7e706)

**Comment by rufuspollock** [comment]
@mohamedsalem401 i can't see this well documented now on the site. This should be a little feature page on its own - can you check if this is written up and if so reference it here. And if not let's write it up briefly (and check it still works)
