### ISSUE TITLE
Use typescript

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#13]
Shall we use typescript? Pros and cons please ... **UPDATE: we will trial it ...**

## Acceptance

* [x] Made a choice about trialling
* [x] Do basic setup (what is required?)
* [x] Start using
* [x] Summarize experience and whether we go 100%

## Tasks

- [x] migration analysis
- [x] switch from JS to TS in CLI package **done #300**
- [ ] switch from JS to TS in the template package

## Analysis

Since TS is a superset of JS, migration to 100% TS codebase can be gradual. Also, Nx has native TS support so all the workspaces and projects in our repo will already include basic ts.config.json files and should already support TS out of the box.

### Suggested approach

* Add support for TS to the existing codebase
  - ts compiler configurations,
  - add build step for the CLI,
  - start creating `d.ts` declaration files to enable type-checking of the existing JS code by the TS compiler (the additional benefit at this point is auto-completion support in code editors)
  - write all NEW files in TS
* Slowly start refactoring existing JS files to TS.

#### Making template package work with `tsconfig.json` file instead of our original `jsconfig.json`

**TL:DR:**
`npm run dev` --> Next.js sees the `tsconfig.json` file and adds `jsx: preserve` compiler option (or overrides it) --> Contentlayer's esbuild picks up the changed `tsconfig.json` file --> JSX in md files is not converted to JS --> errors!

Problem: contentlayer is not converting JSX to JS when used with Next.js + `tsconfig.json` file.

**Context:** When Next.js sees the `tsconfig.json` file in the project (template), it overrides some of the values that are required to make Next.js work as expected and they don't have the option to opt out of it. One of these properties is `jsx`, which by default is set to `react`, but Next.js will change it to `preserve`.

> react: Emit .js files with JSX changed to the equivalent React.createElement calls
> preserve: Emit .jsx files with the JSX unchanged

Next.js does it because they claim they have better way of converting JSX to JS, so they don't want the ts compiler to do this. However, the same ts.config.js file will be picked up by Contentlayer's esbuild and so it will not convert JSX to JS with React elements.

**Comment by rufuspollock** [comment]
Talking to others it sounds like typescript is a good idea. So we shall do it.

**Comment by rufuspollock** [comment]
@olayway we haven't yet switched to this have we? I think the plan is to do so and probably requires some minor setup. If so can we note the commits and/or updates?

**Comment by rufuspollock** [comment]
@olayway could we do a quick look (1h or so) to get a sense of how much work this is and the pros/cons? I note that eg. pliny uses typescript and seems to be direction of travel for many projects.

**Comment by olayway** [comment]
@rufuspollock this is still not working in the template due to the `jsx` field being overridden by Next. Contentlayer does have an example repo with Next + TS, but they are not using MDX, but MD, so `jsx` set to `preserve` doesn't cause any problem as `esbuild-mdx` doesn't parse any JSX, only MD.

**Comment by olayway** [comment]
I've just submitted an issue in the Contentlayer repo: https://github.com/contentlayerdev/contentlayer/issues/334
