### ISSUE TITLE
CLI v0.1

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#134]
Skeleton a basic CLI app in packages/flowershow and publish to npm

I want to run `npx flowershow` and get a help message

## Acceptance

* [x] Can run `flowershow` or `npx flowershow` and it outputs a simple help message **✅ 2022-09-07 works**
* [x] published to npm **✅ 2022-09-07 published**
* [ ] Test (?) - normally best approach is to split into a core lib and cli wrapper and you can test core lib **I think I'll add tests while working on the actual logic for the commands**

## Tasks

* [x] Research
  * [x] Choose command line library (with reasons)
  * [x] Examine other good open source command line tools in node (e.g. vercel, even old https://github.com/datopian/data-cli)
* [x] Skeleton it out and have help message
* [x] Publish

## Notes
Most popular tools for creating CLI tools seem to be:
1. **commander** (alternatives: **yargs**, **minimist**, **oclif**, **argh**, and others)
  - tool for defining commands, parsing arguments, displaying errors, and help
    > Commander looks after parsing the arguments into options and command-arguments, displays usage errors for problems, and implements a help system.
2. **inquirer**
  - for inquiry sessions, possibly with fancy menus (e.g. like vue-cli)
  > provides the user interface and the inquiry session flow
  > providing error feedback, asking questions, parsing input, validating answers, managing hierarchical prompts
3. **chalk**
  - for cool terminal string styling
4. **winston**
  > For consistent formatting of log output and ease of applying things like prefixes

### commander vs yargs vs minimist vs oclif
- it's rather a matter of preference...
- minimist is very...minimal - it only helps with arguments parsing (I'd rather choose sth more convenient/easier to use e.g. commander)
- commander has no dependencies
- vue-cli and datopian-cli are using minimist+inquirer+chalk

**Comment by olayway** [comment]
@rufuspollock I'd go with commander + inquirer + chalk combo for now. As for commander choice - its really a matter of preference (from what I've learned on reddit and blogs) and IMHO doesn't matter all that much. I've just tested commander and it's very easy to use and logical. But if you've used another tool and would rather use it - I can work with it too.

**Comment by rufuspollock** [comment]
@olayway sounds great. Let's go with that.

**Comment by olayway** [comment]
@rufuspollock the basic CLI tool is already on the `main` branch, as I wanted to publish it to npm already with the correct repository URL in `package.json`.
I've published it on my private npm to do some testing so you can check how it works with `npx testinglola --help`. But basically it looks like this:

![image](https://user-images.githubusercontent.com/52197250/188871922-c85d1cd8-194c-4c4b-9cef-b7578951c5d5.png)

![image](https://user-images.githubusercontent.com/52197250/188872077-76aa2d2c-4f82-45ed-b0a7-86bf3b3afaaa.png)

![image](https://user-images.githubusercontent.com/52197250/188872184-560b8fa0-88cd-40b8-8f19-de2fac20a1c2.png)

Two questions:
1. I've put the CLI tool in `/cli` directory of this repo, but let me know if you want to keep it somewhere else. I wasn't sure if you'd like it to go inside `/packages` maybe?
2. Do we want to publish it as a scoped package under our Flowershow npm org? In this case, it will be available under `@flowershow/<package-name>`, like e.g. on the screenshots above.

**Comment by olayway** [comment]
@rufuspollock I've moved the cli to `/packages/flowershow` and published under `flowershow`. You can test it with `npx flowershow`. As for tests, I'll add them while working on the actual logic of the commands.
Let me know if I can close this issue.

**Comment by rufuspollock** [comment]
@olayway great - let's close. 👏
