### ISSUE TITLE
Support obsidian wiki links

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#14]
Use https://github.com/flowershow/remark-wiki-link-plus

## Acceptance

* [x] Obsidian wiki links e.g. `[[...]]` are working **✅ 2022-07-08** [/demo/wiki-links](https://flowershow.app/demo/wiki-links)
* [x] Bonus: also document in developer section how we add remark / rehype plugins **✅ 2022-07-11** [/meta/developers](https://flowershow.app/meta/developers)

![Screen Shot 2022-07-11 at 5 34 18 AM](https://user-images.githubusercontent.com/42637597/178243187-dbaab4e6-c293-42b0-b041-f4d6ac5cf561.png)

## Tasks

* [x] Add a "test" (e.g. add to a demo page and then add a proper test)
* [x] Add the plugin
* [x] Document in e.g. `/meta/developers`

**Comment by rufuspollock** [comment]
@khalilcodes the demo should have a working example not just the code for doing it. Could we add that?

**Comment by rufuspollock** [comment]
FIXED. Actually all working. Note will move docs/demo to https://flowershow.app/docs/wiki-links
