### ISSUE TITLE
"Edit this page" link on pages

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#143]
When creating a wiki-like site (or docs site) based on a public repo i want to be able to edit this page link on pages so that people (including me the editor) can quickly edit a page and make changes

NB: believe we have already implemented this on web3 so this is a backport

## Acceptance

* [x] Edit this page link at bottom of pages linking to right section on repo
* [x] Edit this page can be enabled / disabled (disabled by default) in config
* [x] Edit this page can be enabled / disabled per page via frontmatter option

## Tasks
* [x] Fork Flowershow main and create a branch for this issue
* [x] Edit this page link at bottom of pages linking to right section on repo. **added link to layouts.js**
* [x] Edit this page can be enabled / disabled (disabled by default) in config. **editLinkShow: false added**
* [x] Edit this page can be enabled / disabled per page via frontmatter option. **editLink with default: editLinkShow**
* [x] Review whether all changes work as it should

**Comment by rufuspollock** [comment]
@PhilippeduPreez note none of the acceptance items are updated with any comment as per https://tao.lifeitself.org/issues/#completing-tasks and no closing remark generally https://tao.lifeitself.org/issues/#closing-issues

I'd particularly like here to see some kind of link to the documentation for this. Also is this enabled on flowershow.app?

**Comment by PhilippeduPreez** [comment]
FIXED
"Edit this page" links option can now be configured in config.js file as well as in the frontmatter of each page. See [updated docs](https://github.com/flowershow/flowershow/blob/main/site/content/docs/edit-this-page.md)

**Comment by PhilippeduPreez** [comment]
@rufuspollock the default is currently disabled
