### ISSUE TITLE
Developer Docs v0.1

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#149]
As a new contributor I want to know how to get started so I can make a contribution

## Acceptance

* [x] Brief overview of layout of repo e.g. nextjs template app in `templates/default`, flowershow.app site (which acts as sort of demo) in `site`
* [x] How to get template app running
* [x] A single starting point for contributors at https://flowershow.app/docs/contributors (can just be a brief summary with links to other readmes or docs or can be the full thing) **2022-12-01 moving everything**
  * [x] remove content of contributors section on main repo readme and move here (keep section in readme with only content being link to the docs)
  * [x] mono repo docs @olayway created linked from here (or merged)

## Tasks

TODO

**Comment by rufuspollock** [comment]
@olayway great work as usual.

One point re process: please can we have short summary here when we close - not just in PR. e.g. here you could just say:

FIXED. Consolidated all developer docs in https://flowershow.app/docs/contributors

Also i note that https://github.com/flowershow/flowershow/blob/main/README.dev.md still exists and seems to be a duplicate of content in https://flowershow.app/docs/contributors (?)
