### ISSUE TITLE
Simplify imports of custom components and data

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#154]
## User story
As a user I want to be able to use simple import paths to easily import my custom components and custom data into MDX files.

## Acceptance
- [ ] custom data can be imported with a simple import path, e.g. `import exampleData from "data/exampleData.json"`
- [ ] custom components can be imported with a simple import path, e.g. `import MyComponent from "custom/MyComponent.jsx"` 

## Tasks
- [ ] research how to create custom path resolutions in MDX files
  - [ ] is it even possible when we're using Contentlayer?
  - [ ] do we need to create a custom mdx loader that would somehow do its work before Contentlayer takes over?
- [ ] think about how to create such path resolutions dynamically, based on where the user has his `components` or `data` folder

## Notes

At this point when we're trying to import custom data, that is located in `/site/data`, into MDX file the path looks like this:
```md
import exampleData from "../../site/data/exampleData.json"
```
For custom components we've simplified this path a bit (or at least made its usage easier - same as for importing template components) by creating a symlink to `/site/components` in `/templates/default/components` (under `custom` name), so the path looks like this:

```md
import MyComponent from "../components/custom/MyComponent.jsx"
``` 

instead of 
```md
import MyComponent from "../../site/components/MyComponent.jsx"
```

**Comment by olayway** [comment]
FIXED with 3897be239dca944c4a256c26163b0a488a2e619c thanks to adding `cwd: process.cwd()` in `contentlayer.config.js`.
