### ISSUE TITLE
Make (site) config and page frontmatter available as variables in a given page

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#155]
When creating a page / post I want to include some info from the frontmatter or the overall site config (e.g. site description) so that i don't have to write the same thing in two places (??)

## Acceptance

- [ ] site config is available as a variable called `config` so i can do `{config.title}` to get site title in body of the page
- [ ] frontmatter available as `frontmatter` so i can do `{frontmatter.title}` in the md(x) body of a page

## Tasks

- [ ] See notes below for how to add this

## Notes

We can make a given variable globally available (defined for every MDX page) by adding it in an object passed as the second argument of Contentlayer's `useMDXComponent`, like so:

```js
// [[...slug]].js
...
const someData = {};
const Component = useMDXComponent(body.code, { someData });
...
```

**Comment by rufuspollock** [comment]
WONTFIX. Not a big deal atm and not a major use case.
