### ISSUE TITLE
Page comments / discussions

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#163]
When publishing a page I want to allow visitors to post comments so that I get feedback

* want to be able to bulk enable/disable e.g. in settings
* enable/disable page by page

Implementation: suggest we build on (and contribute to) pliny, see https://github.com/timlrx/pliny/tree/main/packages/pliny/src/comments

## Acceptance

* [x] Commenting support on posts and pages **✅ 2023-02-01 (we are using discussions "Announcements") merged in commit ...**
- [x] Enable page by page in frontmatter:
```md
---
showComments: true 
---
```
- [x] Bulk enable in config:
```js
const config = {
  comments: {
    pages: ["blog"] // can add more in array eg. docs
  }
}
```
<img width="1429" alt="Screen Shot 2023-01-30 at 1 35 11 PM" src="https://user-images.githubusercontent.com/42637597/216130653-931711fd-6fd4-40a6-8230-f89c8e3f1c2e.png">

## Tasks

Research / Design

**✅ 2023-01-25 Using pliny approach but with imported components from providers**

- [x] how does it work roughly
- [x] what do you think of it? (tech and design wise) i.e. pliny implementation
- [x] what is recommended approach in terms of approach and implementation
	- [x] should we follow this approach or look at something else
	- [x] what are the key tasks
- [x] how long will it take guesstimate? (for MVP and polished)

Implementation 

**✅  2023-01-31**

- [x] Create comments components in core for [giscus](https://giscus.app/), [utterances](https://utteranc.es/) and [disqus](https://disqus.com)
 - [x] Add and use [giscus react](https://github.com/giscus/giscus-component) and [disqus-react](https://github.com/disqus/disqus-react) packages in core 
- [x] Add configs in frontmatter and config.js
  * configured to set page comments through frontmatter, or specified folders in comments' config. If both are not set then defaults to show on all pages. Frontmatter value takes precedence.
- [x] Add documentation @ [docs/page-comments](https:/flowershow.app/docs/page-comments)
- [x] publish core package to npm
- [x] Add giscus env variables in netlify
- [x] install giscus app in flowershow repo

## Notes

> 1. how does it work roughly
* provider components are setup in let's say `core/ui/Comments` and rendered based on config values - `GiscusConfig | DisqusConfig | UtterancesConfig`.
* cors setup in `next.config.js` and env variables
* Component is imported in either the whole layout or Blog's layout file if we only want them for posts.

> 2. what do you think of it? (tech and design wise) i.e. pliny implementation
* This works really well for multiple providers and also scalable for adding more. If we are not using more than one provider, then it's probably a single component imported in our `Layout.tsx` which is rendered based on config and pageProps values.

> 3. what is recommended approach in terms of approach and implementation	
> should we follow this approach or look at something else
	 
If we are looking to use a single provider but are not sure about adding more in future, then this approach would be the route to take. My thoughts are since this is a plug it in kind of model and because provider components can be replaced easily, I would be leaning to use this. But I'm also interested to research what are the other ways this can be implemented.
	
> what are the key tasks 
     
- components in core package
- configs and env variables
- Comments either in app layout or specific to Blog layout

> 4. how long will it take guesstimate? (for MVP and polished)
* MVP ~3hrs or more if using some other provider not used by pliny. First pass would be just using the same setup and provider and see if that is working. Then modifying stuff according to our needs eg. based on additional configs.
* polished ~6hrs more or less with design suited to flowershow

**Comment by khalilcodes** [comment]
notes on implementing this - https://hackmd.io/@khalil/B1-a8c2is/edit

**Comment by rufuspollock** [comment]
@khalilcodes thanks for update. Could you give a bit more detail on our "standard" (as of yesterday 🤣) questions:

- how does it work roughly
- what do you think of it? (tech and design wise) i.e. pliny implementation
- what is recommended approach in terms of approach and implementation
  - should we follow this approach or look at something else  
- how long will it take? (for MVP and polished)

**Comment by khalilcodes** [comment]
@rufuspollock I have added some answers in description notes.

**Comment by rufuspollock** [comment]
@khalilcodes i would support multiple providers like Pliny.

**Comment by rufuspollock** [comment]
@khalilcodes and @olayway great work everyone 👏 

Quick questions / comments:

- docs page naming: why `page-comments` vs `comments`? `comments` seems simpler and i assume this applies to blog pages as well etc?
- could we get a `created` date on the page
- shall we turn this docs page into a blog post by adding `type: Blog` (seems worth of it!)
- have we turned this on for the site? if so where can i try it out?

Finally when closing issues (and i know this closed by PR) can we copy over some info especially on "big" issues like this one so that when looking at issue in roadmap or board it is easy to see what happened. Here just a link to docs page and a FIXED would have been sufficient i think!

**Comment by khalilcodes** [comment]
@rufuspollock 
> have we turned this on for the site? if so where can i try it out?

it's turned on for blog pages atm for eg. https://flowershow.app/blog/2023-01-25-updated-features
Also, the comments will go into the dicsussion's category - Announcements, but I think it's best to change this by creating a new category called comments.

Will do the other changes 👍

**Comment by rufuspollock** [comment]
> Also, the comments will go into the dicsussion's category - Announcements, but I think it's best to change this by creating a new category called comments.

Yes, is this configurable? And generally, i assume this is just a default category for new comments - e.g. if i later move that comments thread in github got another category nothing happens. Also can you document a bit how this actually works in terms of the id linking of a page to a thread in github discussions (this can just be linking me to the docs in giscus). This applies to a use case i am thinking of where i start out with a discussion on github, i turn it into a page in flowershow and want to configure the setup so i can link to the existing comments thread.

Re the other changes: can you hoist them them to tasks in the main description and check them off just so we know where we are.

**Comment by khalilcodes** [comment]
@rufuspollock done and updated in description (How it works and tasks). Adding links below also:

https://giscus.app/ (see Page <-> Discussions Mapping section)
https://github.com/giscus/giscus#how-it-works

**Comment by rufuspollock** [comment]
@khalilcodes 👍 and could we have that info in the docs for the feature (maybe in developer section).

**Comment by olayway** [comment]
> @khalilcodes 👍 and could we have that info in the docs for the feature (maybe in developer section).

@khalilcodes is this done?

**Comment by khalilcodes** [comment]
@olayway done in commit [ccd893e](https://github.com/flowershow/flowershow/commit/ccd893e1fb6005fb04104e791d6e7ceb51e35070)
