### ISSUE TITLE
Non-algolia search support (ootb search with no external deps)

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#169]
When running my site I want search either using something fancy like algolia (if i qualify and can setup) or using something without dependencies so that people can find things quickly

Follow up to #34 where we implemented algolia.

Suggest we move to using pliny search setup: https://github.com/timlrx/pliny/tree/main/packages/pliny/src/search (see more discussion below)

## Acceptance

- [ ] Algolia still works
- [ ] Have non-algolia "built-in" search (following pliny probably)
- [ ] Updated https://flowershow.app/docs/search 

## Analysis

I suggest we move to using pliny approach to search which supports algolia and inbuilt solution - see https://github.com/timlrx/pliny/issues/26. Actual implementation is in https://github.com/timlrx/pliny/pull/35

As this is very well designed and modularized i believe we can largely reuse the component quite cleanly, see e.g. https://github.com/timlrx/pliny/pull/35/files#diff-3d648d6c4a1017daf334b58014aac23abd21ad0c73e208af53e6640bc6223c80R16 where in `_app.tsx` we have:

```jsx
import { SearchProvider } from 'pliny/search'

...

      <SearchProvider searchConfig={siteMetadata.search}>
        <LayoutWrapper>
          <Component {...pageProps} />
        </LayoutWrapper>
      </SearchProvider>
```

**Comment by khalilcodes** [comment]
@rufuspollock @olayway started to work on this yesterday with good progress.

One question is that should we now keep the algolia keys etc in `config.js` similar to pliny's approach ? They are public anyways imo.

**Comment by khalilcodes** [comment]
@rufuspollock  @olayway Kbar generates a `search.json` but after deploy in latest PR #248 it doesn't seem to pick up the json file leading to empty results in search.

**Note:** It did seem to work on first deploy before doing a git rebase to latest flowershow and also works when I did a deploy preview of the 'out' directoy on a separate netlify account - https://636bbbb7260c5c6ad29b58ab--previews.netlify.app/

**Comment by olayway** [comment]
Closed with #248
