### ISSUE TITLE
Code highlighting

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#17]
Nicely render code blocks in markdown

Suggest we use e.g. use https://github.com/timlrx/rehype-prism-plus

## Acceptance

* [x] Code sections are nicely rendered (i.e. syntax highlight) **✅ using rehype-prism-plus**
* [x] Have an example in demo page **✅ [/demo/code-highlight](https://flowershow.app/demo/code-highlight)**
* [x] Bonus: copy and paste button **seen on hover**

![Screen Shot 2022-07-12 at 6 25 51 AM](https://user-images.githubusercontent.com/42637597/178402172-9e04d2d0-2fc0-4daa-bb3f-422d3ce21f1b.png)

## Tasks

* [x] Do we use prism or highlight.js. **✅2022-06-29 Answer: prism i think (same speed, more plugins (?))**
* [x] Add the plugin **✅ 2022-07-11**
* [x] Add a section to demo to show it **✅ 2022-06-11**
* [x] Copy/paste button **✅ 2022-07-11**
   * [x] Add component `Pre.js` to mdx
* [x] Styles used - prism vs code dark from https://github.com/PrismJS/prism-themes

**Comment by rufuspollock** [comment]
FIXED. Looks great. See https://flowershow.app/demo/wiki-links

PS: @khalilcodes one thing is i think rather than having in demo i think we put this in /docs/ since it is basically documenting and demoing a feature.
