### ISSUE TITLE
e2e test for CLI v0.1

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#173]
Test our CLI v0.1 self-publishing `npx flowershow` workflow end to end with continuous integration

## Acceptance

* [x] Have an e2e test of installing and building and publishing with github pages **deploying on Netlify**
* [x] Install works
* [x] Build works
* [x] Publish works (github pages) **deploying on Netlify for now**

## Tasks

* [x] Choose whether to create a repo or folder in our existing rep **✅2022-09-14 ?? using a folder in our repo is probably easiest for now as triggering is easy**
* [x] Create `tests/cli-e2e` with markdown fixtures e.g. index.md
* [x] Add a markdown file or two
* [x] Create a github workflow to run the build using flowershow (and publish the output e.g. to github pages or netlify or ...) **2022-10-17 100% done** **deploying on Netlify**

## Notes
**2022-10-11** using [expect](https://linux.die.net/man/1/expect) for interacting with the CLI and [bats](https://bats-core.readthedocs.io/en/stable/tutorial.html) for writing tests.
