### ISSUE TITLE
Feature Testing using playwright round 2 part I: clean fixtures site

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#174]
We have playwright working, we just aren't testing very much with it ...

## Acceptance

* [x] e2e tests with playright are testing stuff again that is in templates/default and not in the app **✅2022-09-20 see commit https://github.com/flowershow/flowershow/commit/b7ca935ce9b19ca7c0aa599270483de82ff03289 and see running build with new test setup https://github.com/flowershow/flowershow/actions/runs/3089822372/jobs/4997867883**

## Tasks

* [x] Where do put our markdown fixtures for testing? **✅2022-09-14 `templates/default/tests/fixtures`**
  * In site/content/tests` ** very ugly and bad smell**
  * In `templates/default/test/fixtures`? Problem: how do they get rendered? **✅2022-09-14 Ans: github workflow that deletes content (and assets) symlink and replaces it with symlink to fixtures and then runs stuff ...**
* [x] Create one test and fixture
* [x] update npm test to do this symlinking automatically (?) or even better do it one-off test setup (and teardown - so you don't break your local system)
* [x] Update github workflow (if needed)

**Comment by rufuspollock** [comment]
FIXED. All working.
