### ISSUE TITLE
Alpha Release of Flowershow Self-Publishing

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#179]
## Acceptance

* [x] Docs are ready to use **🚧 reviewed, changes tbd**
* [x] Front page summary links to docs **PR (draft) #209**
* [x] Forum issue for this inviting people to give feedback **created [here](https://github.com/flowershow/flowershow/discussions/215)**
* [x] Emailed our alpha list to try it out - point to docs and discussion issue **used mailchimp**
* [ ] Posted on obsidian forum, maybe on reddit
* [ ] dev.to post from philippe

## Tasks

* [x] Identify and review key docs (and any changes to be made) **reviewed the docs below**
  * [x] Follow self publishing tutorial to make a flowershow site (`publish-tutorial.md`) **2022-10-18 olayway: working on updates, 50% done**
  * [x] Testing basic config (`config.md`)
  * [x] Testing markdown features (`syntax.md`)
  * [x] Testing Mdx components (`mdx.md`)
  * [x] Tailwind (`tailwind.md`)
  * [x] TOC (`table-of-contents`)
* [x] Front page summary changes
* [x] Github forum issue in github discussions created. **created [here](https://github.com/flowershow/flowershow/discussions/215)**
* [x] Email alpha list **using mailchimp**

Pause for maybe 2d

- [ ] #216

**Comment by olayway** [comment]
@PhilippeduPreez we didn't want to post it yet! 😅 Just add a link to HackMD here. + please add a list of docs pages you've reviewed. Thank you!

**Comment by rufuspollock** [comment]
@PhilippeduPreez please update here as we do things e.g. update acceptance and add comment in comments thread.

**Comment by olayway** [comment]
Fixed, follow-up issue in https://github.com/flowershow/flowershow/issues/226
