### ISSUE TITLE
Changeset config

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#188]
## Problems
- We have two `.changeset` folders atm - one in the root folder and one in `templates/default`
  - adding changeset via GH creates a changeset file in the root directory

## Acceptance
- [ ] changeset file is always added to `templates/default/.changeset` folder

## Tasks
- [ ] check if where the changeset file is created depends on where we run `npx changeset` command
- [ ] check if we can configure it (for changeset CLI and on GH) to always be added in `templates/default`

**Comment by olayway** [comment]
@khalilcodes any progress here?

**Comment by olayway** [comment]
@khalilcodes I've updated the acceptance, as we don't really want to bump the version each time we run `npx changeset`. We only want to do this when we make a release - and for figuring this out we have another issue, which we will work on later on.

**Comment by PhilippeduPreez** [comment]
I am only able to run npx changeset in templates/default, so  the changeset file will be created in the same place

**Comment by PhilippeduPreez** [comment]
I have added an issue [here](https://github.com/changesets/bot/issues/60) for the changeset-bot we are currently using in Github. The isn't any documentation on any possible config changes and it does not seem like issues are worked on, since there is a lot of issues from 2021. I also believe I do not have access to the github apps/bots we currently use.

**Comment by PhilippeduPreez** [comment]
I think in order to make any changes to the bot, we would have to fork the repo and make our own bot. For now we should just add changesets with npx changeset inststead of using the bot.

**Comment by rufuspollock** [comment]
@olayway can we close this now either as WONTFIX or FIXED after your work on monorepo and changesets?

**Comment by olayway** [comment]
FIXED with #18
