### ISSUE TITLE
Set up discord chat channel and add to site

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#203]
Following [discusssion](https://github.com/flowershow/flowershow/discussions/186) have decided to create chat channel on discord for community to chat and engage.

## Acceptance

- [ ] Discord "server" setup for Flowershow **✅2022-10-12 - see https://discord.gg/aeZbNd2z**
- [ ] @olayway and @rufuspollock admins for now **✅2022-10-12 made admins**
- [ ] Chat/discord link on flowershow.app site (navbar for example)

## Tasks

- [ ] Setup server **✅2022-10-12 **
- [ ] Make admins **✅2022-10-12 **
- [ ] Add to flowershow.app site

**Comment by PhilippeduPreez** [comment]
FIXED [here](https://github.com/flowershow/flowershow/pull/204/commits/6450379b7d5541aa1b6bfcc9469a056ac263027b)
