### ISSUE TITLE
Alpha release sharing on different forums

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#216]
Blog post on flowershow plus sharing on relevant fora ...

## Acceptance

- [x] "blog post" on flowershower.app (for now just in a new blog folder - can replicate the content in the discussion forum post) **2022/11/07 https://github.com/flowershow/flowershow/blob/main/site/content/blog/alpha-release.md**
- [x] Posted tutorial/intro on dev.to (and medium?)
- [x] Posted on reddit, obsidian forum etc

## Tasks

- [x] follow-up email sent out to people who haven't opened the original alpha-release email
- [x] Draft announce(s)
  - [x] short alpha release announcement for reddit and Obsidian forum **✅ 2022-10-27 draft created here https://hackmd.io/y0D3I2bQRhyzgA_YhpUhXQ**
  - [x] longer, more "sophisticated" and elaborate version for medium and dev.to **✅ 2022-10-28 draft ready https://hackmd.io/qdIQhRyKQuamDa4lvGeEvQ**
    - more or less this should include what we have in our self-publishing tutorial + some nice intro and summary/conclusion
- [x] Post up on flowershow "blog" **2022/11/07 https://github.com/flowershow/flowershow/blob/main/site/content/blog/alpha-release.md**

Sharing

- [x] Identify places to post 
- [ ] Post on those places 
  * [x] obsidian forum **✅ 2022-10-27 done https://forum.obsidian.md/t/alpha-release-of-flowershow-s-self-publishing/46262**
  * [x] reddit **✅ 2022-10-27 done https://www.reddit.com/r/ObsidianMD/comments/yeb8gy/alpha_release_of_flowershows_selfpublishing/**
  * [ ] twitter
  * [x] dev.to **✅ 2022-11-07 https://dev.to/flowershow/publish-your-obsidian-vault-with-flowershow-48ip**
  * [x] medium **✅ 2022-11-07 https://medium.com/@olarubaj/publish-your-digital-garden-with-flowershow-c45509dfd4e0**
  * [x] hacker news **2022-10-31 https://news.ycombinator.com/item?id=33404028**
~* [ ] Obidian publish alternatives' threads on Obsidian Forum, reddit etc.~
     ~* [x] obsidian-zola **2022-10-31 [here](https://www.reddit.com/r/ObsidianMD/comments/u3irg6/a_free_simple_good_looking_alternative_to/)**~
     ~* [ ] perlite~
     ~* [ ] pubsidian~
     ~* [ ] MindStone **2022-10-31 Post was removed**~
     ~* [ ] Obsidian Diital Garden~
     ~* [ ] Gatsby Garden~
     ~* [ ] Quartz~
     ~* [ ] Markbase~
     ~* [ ] obsidian-userland/publish~
     ~* [x] Obsidian Mkdocs **2022-10-31 Post was removed**~

**Comment by olayway** [comment]
@PhilippeduPreez I think it would be a good idea to also add [hacker news](https://news.ycombinator.com/) to the list. It's very popular among the coding community.

**Comment by PhilippeduPreez** [comment]
@olayway Moderators remove posts if you link your own tool on Obsidian threads. At least that is what I have experienced

**Comment by olayway** [comment]
@PhilippeduPreez Ok, so let's leave Obsidian threads for now and maybe let's see if other alternatives have some reddit threads as well and at least post there? 

And apart from that, the last thing to do here would be:
> Put up a blog post on flowershow with comparison of Obsidian Publish alternatives and Flowershow

**Comment by olayway** [comment]
@PhilippeduPreez I've just posted on dev.to and medium (links in the issue description). Please prepare a short thread for twitter and share with @rufuspollock. And the last thing here would be to create a blog post that will show up on our site and that we could link to e.g. in the twitter thread.

**Comment by PhilippeduPreez** [comment]
@rufuspollock https://hackmd.io/JJXYyhl2Q_GRqvuiL6dw-w twitter alpha release post
