### ISSUE TITLE
Feature Docs & Demo Page(s) v0.1

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#22]
Create some demo pages that show off the features. This could be all in one or spread out over the features in docs.

## Acceptance

* [x] All core features have a docs page e.g.
* [x] Basic markdown markup (can copy this page over from data-literate) **✅2022-07-13 https://flowershow.app/docs/markdown**
* [x] Wiki Links
* [x] Code Highlighting
* [x] Analytics configuration @olayway (tip look at config/siteConfig.js!) **✅2022-07-19 https://flowershow.app/docs/analytics**
* [x] User configuration (very simple - just mentioning existence of `userConfig.js` and (?) explaining how to edit it (?)) **✅2022-07-20 #54**
* [x] Navbar configuration @olayway i.e. edit `navLinks` list **✅2022-07-20 #54**
* [x] Layouts ?? i.e. overall page explaining layouts and then description of two options we currently have (maybe link to demos of them in docs e.g. `/docs/layout-raw` and `docs/layout-docs` **✅2022-07-20 #54**
* [ ] grammar check :stuck_out_tongue:

**Comment by rufuspollock** [comment]
This issue is now not called Demo Page but we still want docs pages for each feature.
