### ISSUE TITLE
Alpha release CLI fixes

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#228]
## Tasks

- [x] change `npx flowershow install` to `npx flowershow@latest install` in our docs **✅ 2022-10-28 [#72e15a7](https://github.com/flowershow/flowershow/commit/72e15a76690572845aa238376d850228ac88efc2)**
- [x] additional info in the console, like:
  - [x] "No config.js / index.md file found in your content folder. Creating one..."
- [x] #235
- [x] #218
- [x] Have `npx flowershow@latest install` rather than just `npx flowershow install` (see https://github.com/flowershow/flowershow/discussions/215#discussioncomment-3931647)
- [x] #212
