### ISSUE TITLE
Default theme v0.1

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#23]
## User story

As a user, I want to be able to start with a basic page layout to publish my content.

## Acceptance

* [x] Front page basic layout
  * [x] Nice hero
  * [x] Rest of page can be markdown (just nicely styled) - cf syntax example after special links section is fine 	
* [x] Rest of pages - have standard markdown styling **✅2022-07-16 looking nice. see screenshot**
* [x] Navbar **✅2022-07-14 it's working** ![image](https://user-images.githubusercontent.com/180658/178975073-560b6373-3b3f-4f69-ad55-8600c08a34ed.png)
* [x] Footer **✅2022-07-14 working now**

![image](https://user-images.githubusercontent.com/180658/179968568-7124da7e-f4a4-4f08-8761-4bf8c14f3da0.png)

![image](https://user-images.githubusercontent.com/180658/179968675-eed1e2c9-2823-409c-838b-7adae675cc8a.png)

Bonus

~* [x] Work out how we refactor this out of the default template (or maybe leave as default template?)~ **Let's treat this as our default template for now, as we don't have any other templates yet. In the future we cant create other ones and [here is the issue for that](https://github.com/flowershow/flowershow/issues/30). (For reference: this issue was previously named "Theme Flowershow Website").**

## Tasks

* [x] Choose a basic theme to use **✅2022-07-08 can try-out tailwind theme e.g. "Syntax"**
* [ ] #55
* [x] Work on front page using MDX and basic copy we have
* [x] Navbar:
   * [x] Refactor `nav` component as in theme template **✅ 2022-07-11**
   * [x] Add component `MobileNavigation.js`
* [x] Hero:  **as per 12/07/22 meeting:  let's just use raw HTML instead of creating react components**
   * [x] Add components  `Hero.js` `Button.js` **✅ 2022-07-11** 
   * [x] Use Hero component in `site/content/index.md`
   * [x] Image for hero
* [x] Have logo in navbar and footer etc **✅2022-07-14 have a decent placeholder. More work in #33**
* [x] Sections
* [x] Fonts **Use default from template**

## Notes

- While adding raw html in index.md for Hero, some styles were not being implemented. On further investigation it turns out that additional `<p>` tags are added to the html based on formatting. for eg in markdown ..
```javascript
<div>
  <p className="...">
    // extra <p> tag added to below text on new line and styles from above not applied
    Some example text here
  </p>

  <p className="...">Some example text</p> // styles applied here and no extra <p> tag
</div>
```

- How are we handling images for users ? Maybe makes more sense to symlink in public/images for now .. ?
- Another way to add components in frontpage can be in the layouts section. For eg. `index.md` can have the docs layout but the `Hero` component will only be available for index page.
```javascript
export default function Docs ({ children, frontMatter, components }) {
  return (
    <div className="prose max-w-full">
	{frontMatter._raw.sourceFilePath === "index.md" && <components.Hero />}
	<div className="max-w-4xl mx-auto py-8">
	  {children}
	</div>
    </div>
  )
}
```
This concept was taken from the tailwind docs theme template (which uses markdown) and we may be able to control rendering of components.

**Comment by olayway** [comment]
@khalilcodes somethings off here as well. Could you please look into it? :slightly_smiling_face:

![image](https://user-images.githubusercontent.com/52197250/179284415-eb7e091c-24a9-430b-b156-1f85686d63b9.png)

**Comment by olayway** [comment]
Fixed!
