### ISSUE TITLE
Switch to using roadmap driven by github projects

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#237]
Follow up from: https://github.com/flowershow/flowershow/discussions/183

Currently we have https://flowershow.app/docs/roadmap plus some stuff listed on the front page.

Suggestion: converge on using a dedicated kanban board that only lists major features (the ones that matter for users). If wanted we can embed or link this from roadmap page.

Why:

* Currently we repeat information in ~3 places:
  * github issues
  * https://flowershow.app/docs/roadmap
  * A segment of front page
* This leads to things getting rapidly out of sync (as has already just happened as of 2022-09-23 where CLI tool is listing as coming soon but is in fact operational)
* Github issues tend to be the real source of truth. Using automation we can keep a kanban board up to date relatively easily

## Acceptance

- [x] have a github projects kanban board for high level roadmap **✅2022-10-12 https://github.com/orgs/flowershow/projects/1/views/7**
- [x] have a process for adding items to this e.g. new label `roadmap` **✅2022-10-30 created new label and started using it**
- [x] roadmap pages on site updated
  - [x] move current content of https://flowershow.app/docs/roadmap to a blog post about roadmap in july (or just remove) **✅2022-11-03 - just removed**
  - [x] update https://flowershow.app/docs/roadmap with brief info about new board etc **✅2022-11-03 updated with link to board and screenshot. **
  - [x] update front page to remove "under construction features" and (? maybe) just link to roadmap page **✅2022-11-03 remove under construction stuff and left (existing) link to roadmap**

## Tasks

- [x] Create github kanban board
- [x] have new label for roadmap stuff
  - [x] use it for key features **🚧2022-10-30 working on this**

**Comment by rufuspollock** [comment]
FIXED. Updated website as per acceptance. Plus gone through issues pretty extensively and added main ones to roadmap.
