### ISSUE TITLE
[inbox][epic] Docs and Site

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#24]
When coming to Flowershow for the first time i want to read the docs to try it out.

This is not a real issue but a catch-all for planning and tracking docs work.

See the 4-fold approach to https://documentation.divio.com

![image](https://user-images.githubusercontent.com/180658/200555900-a0afc8b6-7cee-4ac8-a34c-1b16ad0b1355.png)

## Misc - Jan 2023

Front page

- [ ] clear and up-to-date list of features
- [ ] better call to action
- [ ] clear landing page for user types e.g. digital garden, use for docs, use for ordinary website

Docs

- [ ] up-to-date docs
- [ ] re-org docs
- [ ] site-wide table of contents for /docs paths
- [x] better cloud publishing marketing **✅2023-12-19 done as of nov 2023**

## Tutorials

How to use Flowershow for X (or how we used flowershow for X)

* [x] Self-publishing in general #165 
  * [x] Publish single and obisidan v1 #131
  * [x] Self-publish tutorial v2  #257 
* [ ] Customize front page
  * [ ] Customize hero section #133
  * [ ] Customize whole page
* [ ] Theme your flowershow site
  * [x] Fonts and colors #292
  * [ ] Change navbar
  * [ ] Change footer
* [ ] Tutorial: Add a blog to Flowershow (or Create a Blog with Flowershow)
  * [x] v1 in #35 
  * [ ] Tutorial v1.1 #397 
* [ ] Custom page types and layout e.g. organization profile pages on ecosystem site
* [ ] NextJS template #396

## Howtos

- [ ] Setup SEO for a page or the whole site
- [ ] Access the config and change it
- [ ] Markdown extension addition i.e. add your own remark plugin to do some kind of processing #advanced #customization

## Reference

- [ ] Working with contentlayer and content structuring #advanced #customization

**Comment by olayway** [comment]
Related to Flowershow Self-Hosted which has been deprecated. WONTFIX
