### ISSUE TITLE
Summarize Learnings / feedback from alpha release (on reddit etc)

### ISSUE THREAD

**Issue by PhilippeduPreez** [flowershow/flowershow#249]
Add any feedback/issues from threads here etc for further investigation

## Acceptance

- [x] List the places we posted
- [x] List how many comments we got
- [x] Summarize or excerpt main feedback (+ve, suggestions, bugs etc) - link to source as well
- [x] After triage create issues for key bugs / items (or add to existing issue)

## Places Posted

- Obsidian forums - 0 comments (But did get clicks) [here](https://forum.obsidian.md/t/alpha-release-of-flowershow-s-self-publishing/46262)
- Reddit - 14 comments [here](https://www.reddit.com/r/ObsidianMD/comments/yeb8gy/alpha_release_of_flowershows_selfpublishing/)
- Hacker news - 2 comments [here](https://news.ycombinator.com/item?id=33404028)
- Twitter - 0 comments 
- dev.to - 0 comments [here](https://dev.to/flowershow/publish-your-obsidian-vault-with-flowershow-48ip)
- Medium - 0 comments [here](https://medium.com/@olarubaj/publish-your-digital-garden-with-flowershow-c45509dfd4e0)

## List of issues found by users

- [x] 404 when using wikilinks **- discussion [here](https://discord.com/channels/1029670148824641576/1029670149470556172/1037387204261072896) Issue created #267**
- [x] inline LaTeX input are rendered as separate lines **- link to discussion [here](https://discord.com/channels/1029670148824641576/1029670149470556172/1037911929093628034). Issue created #272**
- [x] CLI doesn't recognize "~" as home directory **- link to discussion [here](https://discord.com/channels/1029670148824641576/1039106742618959913/1040374444817911930). Issue created #273**

**Comment by PhilippeduPreez** [comment]
@olayway Obsidian links to new notes not working.

https://discord.com/channels/1029670148824641576/1029670149470556172/1037387204261072896

**Comment by PhilippeduPreez** [comment]
inline LaTeX input are rendered as separate lines

https://discord.com/channels/1029670148824641576/1029670149470556172/1037911929093628034

**Comment by rufuspollock** [comment]
@PhilippeduPreez can you directly inline here the key points / comments (e.g. directly quote the channel comment) so we don't have to link through (or get link rot later).

**Comment by PhilippeduPreez** [comment]
- using MacOS Ventura latest version in a Macbook Air M1. 
- tried to install selecting an attachment folder and also without selecting it.

![image](https://user-images.githubusercontent.com/44789132/200271636-8697559e-2f07-42d4-b818-cbd145a451c2.png)

**Comment by rufuspollock** [comment]
> inline LaTeX input are rendered as separate lines

This looks like a genuine-ish bug (and hsould be quite minor). Can you split this out to a separate issue and assign to yourself.

**Comment by rufuspollock** [comment]
@PhilippeduPreez as per discussion can you add links to the source of these issues (e.g. comment on reddit or thread on discord etc). And then can we close asap.

**Comment by PhilippeduPreez** [comment]
@rufuspollock  Done
