### ISSUE TITLE
Post info about flowershow on different forums

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#25]
Create a post about Flowershow and publish it on relevant forums.

## Tasks

* [X] Draft copy in gdoc for announce ✅ **2022-08-03 created in [HackMD](https://hackmd.io/4FpZI4wlRL6cXh_wh9Jk5A?view)**
* [X] Identify forums to post in and post there:
  * [x] Obsidian forum ✅ **2022-08-17 [see post](https://forum.obsidian.md/t/flowershow-a-free-open-source-tool-for-publishing-your-obsidian-vaults/41966)**
  * [X] Reddit ✅ **2022-08-23 see posts on [PKMS channel](https://www.reddit.com/r/PKMS/comments/wvqnn2/flowershow_a_free_open_source_tool_for_publishing/) and on [Obsidian channel](https://www.reddit.com/r/ObsidianMD/comments/wvqtzf/flowershow_a_free_open_source_tool_for_publishing/)**

### Forums to post in
- obsidian forum
- reddit channels: [PKMS](https://www.reddit.com/r/PKMS/)
- dev.to (later when more working?)

**Comment by olayway** [comment]
@rufuspollock if we're not going to post on other forums for now, I'll remove it from from the last sprint and leave it in the backlog maybe?

**Comment by olayway** [comment]
Flowershow announced on Obsidian Forum and Reddit
