### ISSUE TITLE
Pricing page (bonus: way to be supporter / donor)

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#252]
When developing flowershow I want a way to get funded and supported so that we can sustain and increase our efforts

## Tasks

- [x] Analyse options e.g. use stripe, open collective etc **✅2025-02-10 use stripe**
- [x] Create pricing for cloud**✅2025-02-10 a long time ago at https://flowershow.app/pricing (own pricing page)**
- [x] Create own pricing page https://flowershow.app/pricing (and link in navbar)
- [x]  🏆 Have a way to be a supporter / donor (can easily embed that in stripe now) (easy to do ...) **✅2025-02-18 ❌ not v important and can leave for now**

### what logseq does

Pricing links to https://opencollective.com/logseq

![image](https://user-images.githubusercontent.com/180658/200185889-b1c744f7-b3bd-432d-9e3e-472a3830158b.png)

![image](https://user-images.githubusercontent.com/180658/200185912-ea9e90ea-5a30-4be9-bd46-576177118f8d.png)

**Comment by rufuspollock** [comment]
Nearly there. We have pricing on https://flowershow.app/cloud

No need to use opencollective for this!

Should create

- [ ] flowershow.app/pricing (own pricing page)
- [ ] Have a way to be a supporter / donor (can easily embed that in stripe now)

**Comment by olayway** [comment]
Pricing page up https://flowershow.app/pricing

<img width="1566" alt="Image" src="https://github.com/user-attachments/assets/5846668f-27eb-4bd9-ad36-03d0087d0332" />

**Comment by olayway** [comment]
Donations can be enabled soon too, once we set it up on Stripe. Here is a preview:

<img width="1566" alt="Image" src="https://github.com/user-attachments/assets/585b70b1-407f-46f7-b3f9-79f2d565e2a0" />

**Comment by rufuspollock** [comment]
@olayway great - let's get this up.

One small thing: i think "Pro" plan should be called "Premium" and  the "Pro" plan sign up link does not work atm ...

**Comment by olayway** [comment]
I've missed your comment. I'll have it up today.

**Comment by rufuspollock** [comment]
FIXED. All done. See https://flowershow.app/pricing
