### ISSUE TITLE
Tutorial: Self-publish tutorial v2 - ultra-simple (maybe video)

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#257]
## Acceptance

- [ ]  Super-simple tutorial on how to publish a markdown file(s) with flowershow
- [ ] As an add-on indicate you can publish an entire directory etc
- [ ] How to add assets (i.e. images etc)

## Tasks

...

## Analysis

**Comment by rufuspollock** [comment]
Next 24h: write out the script and prep files etc.

**Comment by olayway** [comment]
@PhilippeduPreez I've just added some comments to your script

**Comment by olayway** [comment]
@PhilippeduPreez I've just seen your updated version of the script and it's awesome! I think we're ready for the shooting! 🎬 🎥

**Comment by rufuspollock** [comment]
@PhilippeduPreez can you update here and move to in review or close if done?

**Comment by PhilippeduPreez** [comment]
@rufuspollock  Current display of youtube embed. If it looks good enough, I'll push this change and close this issue
