### ISSUE TITLE
Cloud publishing feature analysis

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#259]
Do first pass analysis for Flowershow cloud publishing.

## Acceptance

**✅2022-11-22 see https://github.com/flowershow/flowershow/commit/40d1cfb8ae84476d58d3c1c70def3dbf0c9b590b and commit https://github.com/flowershow/flowershow/commit/40d1cfb8ae84476d58d3c1c70def3dbf0c9b590b**

- [x] job stories written
- [x] ideas for implementation

## Tasks

- [x] write job stories
- [x] outline options
- [x] discuss
- [x] finalize approach for an MVP

**Comment by rufuspollock** [comment]
FIXED. See acceptance and https://flowershow.app/notes/design-cloud-publishing
