### ISSUE TITLE
Assets folder support

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#26]
When I create stuff in `content/assets` (hard-code for now) i want that to show up on the site at `/assets` so my links work in my markdown

FUTURE: assets configurable and set up as part of scaffolding

## Acceptance

* [x] assets folder in flowershow.app works **✅2022-07-21 this is now working.**
* [x] rough docs for this (for now can explain you need to manually symlink and in future you do X) **✅2022-07-22 see https://flowershow.app/docs/essentials/assets**

## Tasks

* [x] Symlink in this repo
* [x] Add docs

**Comment by rufuspollock** [comment]
@khalilcodes i think this is mostly done and we just need a docs page called e.g. `docs/assets` that explains that you put static files in a folder named assets ...

**Comment by khalilcodes** [comment]
@rufuspollock added a rough doc in https://flowershow.app/docs/essentials/assets for symlink and using the assets folder.

**Comment by rufuspollock** [comment]
I think we want this at simple `/docs/assets` and a brief explanation of what assets folder is for (e.g. static files). in obsidian/user content this would obsidian attachments. https://help.obsidian.md/How+to/Manage+attachments

**Comment by olayway** [comment]
docs related to this to be moved under `/docs` folder
