### ISSUE TITLE
Life Itself content migration

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#261]
Transfer all content (pages, blog and images) from Life Itself's wordpress site to next.lifeitself.org repo - https://github.com/life-itself/community

## Acceptance

- [x] Convert all content to markdown using tool - https://github.com/flowershow/wordpress-export-to-markdown-plus
- [x] Migrate converted content to repo eg. pages to `vault/pages`, blog to `vault/blog`, etc

## Tasks

- [x] Convert all content - pages, blog and images **✅ 2022-12-01**
- [x] Migrate content to repo **✅ 2022-12-01**
  - [x] `pages --> vault/pages`
  - [x] `blog --> vault/blog`
  - [x] `images --> vault/assets/images`
- [x] Add custom elements in markdown for image gallery **✅ 2022-12-01**
- [x] Create custom layouts for blog page and blog list **✅ 2022-12-01**
- [x] Resolve image paths in `MDX.js` **✅ 2022-12-02**
    - *see [this comment](https://github.com/flowershow/flowershow/issues/258#issuecomment-1333791367) for more detail on issue with suggested backport*
- [x] Replace fonts with Poppins **✅ 2022-12-01**
- [x] Add tailwind packages **✅ 2022-12-01**

## Notes
- All Pages content have been moved to the `vault/pages` folder which will resolve the paths to pages as `next.lifeitself.org/pages/[:page]`.
- The pagination on the blog list page is WIP and shows only 5 latest posts for now.

## Screenshots

**Page**

<img width="1455" alt="Screen Shot 2022-12-05 at 4 54 14 PM" src="https://user-images.githubusercontent.com/42637597/205642305-d13cfa38-49d3-40fb-a6fb-999f591d59a3.png">

**Blog page**

<img width="1454" alt="Screen Shot 2022-12-05 at 7 05 00 PM" src="https://user-images.githubusercontent.com/42637597/205670730-9cb7c30d-3900-4ed0-a870-f2e9c02872de.png">

**Comment by olayway** [comment]
@khalilcodes let me know how is it going with this task and if you need any help :)

**Comment by olayway** [comment]
Done in #212
