### ISSUE TITLE
Font and color theming for next.lifeitself.org with notes for tutorial and any changes to template app

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#265]
A notes / tutorial write up on how to add fonts and colors to a flowershow site based on while doing the updates on next.lifeitself.org 

## Acceptance

- [x] changes made on lifeitself
- [x] Tutorial / howto on how to do this published as a blog post
- [x] List of recommended changes to template app

## Tasks

- [x] Add a font from fonts.google.com and use that in pages, components. **✅ using this for now ? https://fonts.google.com/specimen/Archivo?query=archivo**
- [x] Set named theme color (yellow) in `tailwind.config.js` and replace in classes. **✅ lifeitself's `theme-yellow`**
- [x] Write a tutrorial on how to add these - ✅ https://hackmd.io/@khalil/S18UOMwHs/edit

**Comment by khalilcodes** [comment]
Closed with PR https://github.com/life-itself/community/pull/192 with pending minor changes in comments.

**Comment by rufuspollock** [comment]
@khalilcodes i'm reopening as i added the acceptance - can you update acceptance here with links to outputs or a note. Especially good to have basic tutorial up.

**Comment by rufuspollock** [comment]
FIXED. Covered now and also have #391
