### ISSUE TITLE
Remove unneded dev files from template installed by the CLI

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#268]
There are still some files that are not needed in the template degitted by the CLI, like: .env.example, .eslintrc.json, jest.config.js, netlify.toml, project.json.

## Tasks
- [x] remove `/specs` folder
- [x] move `netlify.toml` to root
- [x] remove `eslintrc.json`, `jest.config.js` and `project.json` at `npx flowershow install`

**Comment by olayway** [comment]
Done.
