### ISSUE TITLE
Make favicon configurable

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#277]
Currently favicon is hardcoded. Would be nice to make favicon link configurable (plus provide some guidance on how to do an svg one in the docs!)

## Acceptance

- [ ] Favicon configurable from the config
- [ ] Docs for this e.g. docs/favicon

## Tasks

- [ ] Get favicon href from config in `components/Layouts.jsx`
- [ ] Add docs

**Comment by rufuspollock** [comment]
Still the case and quite easy to fix.

**Comment by rufuspollock** [comment]
WONTFIX for now.

**Comment by JimenezJC** [comment]
Hey, any chance I can pick this up? I see it's marked as WONTFIX but this functionality would be nice.

**Comment by blackberry-garance** [comment]
Agreed, it'd be quite nice to implement it. Many users (myself included) use Flowershow for semi-professional blogs or digital gardens, where the default favicon is just off-brand. It's a small detail, but it goes a long way in making a site feel polished and truly one's own.

**Comment by olayway** [comment]
Thank you for your feedback @JimenezJC and @blackberry-garance! I'm reopening the issue.

**Comment by olayway** [comment]
FIXED https://flowershow.app/blog/how-to-set-custom-favicon
