### ISSUE TITLE
RHS ToC some headings don't show up

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#284]
Comment from @rufuspollock in https://github.com/flowershow/flowershow/issues/95#issuecomment-1301209125_
   
> @khalilcodes when closing a substantive issue like this can we get a bit more info e.g. a screenshot and/or link to example pages - that is really useful when reviewing the issue.
>
> also wanted to flag what seems like potentially buggy behaviour on e.g. this page: https://flowershow.app/meta/publishing-design. Here a whole set of headings don't show up in ToC on RHS (my guess is because nested within a h1). Questions:
> 
> - I would assume h1 other than very first "title" h1 would show up in ToC (though i'm not totally certain about this or how complex to do0
> - even if h1 does not show up i would imagine the h2/h3 etc underneath it would show up ...
>
> ![image](https://user-images.githubusercontent.com/180658/199598300-79d48d37-d9e7-4f90-b694-7bb594a7fd19.png)   

# Acceptance

- [ ] RHS ToC working on pages
- [ ] Missing headings show up

# Tasks
- [x] Move all ToC functions to core
- [x] Headings for h1, h2 and h3
- [x] Page Title heading not in ToC.
  - This is setup to check for fronmatter title or h1 heading as first row (eg. `# Page Heading` and only if frontmatter title doesn't exist)
