### ISSUE TITLE
Blog v0.1 (MVP)

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#296]
Create a basic blog system with index component and way to create individual blog posts.

See #35 parent epic for overview of the feature.

## Acceptance

- [x] Blog list getter that finds all blog-type pages (how blog type is defined is up to implementor but simplest is to use `type: blog` or similar in front matter)
  - [x] shows items in reverse date order
  - ~[ ] (? for MVP could just show all blog posts - most blogs are small) read more / infinite scroll for reading more posts~ **moved to #317** 
- [x] Blog index component that can be used in a page
- ~[ ] Layout for blog pages - take inspiration from vercel/nextjs blog or tailwindcss etc~ **moved to #317** 
- [x] Blog setup on flowershow.app at `/blog/` using that component
- [x] At least one blog on flowershow.app (probably in `/blog/` directory)
- ~[ ] Docs for feature as tutorial blog post~ **moved to #318** 
- [x] Blog link in navbar called `Blog`

Future (and not included atm):

- ~[ ] support for tags on blog posts~ **moved to #317** 
- ~[ ] search of blogs~ moved to **moved to #317** 

## Tasks

- ~[ ] (Stub briefly) tutorial blog for this feature - great way to iron out kinks in UX~ **moved to #318**
- ~[ ] Create a test for this feature~ **moved to #317**
- [x] Create BlogSearchAndListResults component (take allBlogsSummary argument)
- ~[ ] Create individual blog layout page~ **moved to #317**
- [x] Add document type to content layer
  - [x] Add layout automatically as a computed field (#todo does this work ok (i.e. will layout get picked up in nextjs rendering)? assume so as contentlayer processing hapens first ...)
- [x] Create example blog index page at `/blog/` and use component
- ~[ ] Finish tutorial blog~ **moved to #318**
- ~[ ] Create docs page (can reuse tutorial a bit and point to tutorial)~ **moved to #318**

**Comment by olayway** [comment]
@rufuspollock I've used tailwindui components, as I think it matches the rest of our design best. Let me know if it looks good to you

![Image](https://user-images.githubusercontent.com/52197250/203278466-4d33a5b8-d0d8-4558-9919-56e8d3b17716.png)

**Comment by olayway** [comment]
And I think we don't really need a dedicated layout for the blog pages or this MVP version. Rather, I'd suggest extending the default (docs) layout so that it can display the date and authors if they exist in the frontmatter. Later on, when we need some more customizations, we can create a separate layout.

**Comment by olayway** [comment]
@khalilcodes let me know what you think about the above layout 👍 or 👎 ? 😄

**Comment by khalilcodes** [comment]
@olayway Nice !! 🔥 👍

**Comment by rufuspollock** [comment]
@olayway tip: keep the tutorial basic to start with - we can make perfect after first merge!

**Comment by olayway** [comment]
@rufuspollock Sure just had to spend some time helping the users on discord and debugging stuff but I'm working on it now so the PR should be ready in ~2-3h
