### ISSUE TITLE
Auto-extract title and description for a page

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#297]
Be nice if we didn't have to specify title and description in frontmatter especially for e.g. blog posts.

Could we auto-extract title as line 1 heading (if it exists) and extract description as first X characters/words or first paragraph of page?

Bonus: also set up "updated" date for a post based on e.g. last modified in git (if running off git!)

Here's an issue showing how to extract the description (aka excerpt): https://github.com/contentlayerdev/contentlayer/issues/76

NB: should we have description and excerpt be different?

## Acceptance

- [ ] if title and/or description already in frontmatter they are used (if non-empty)
- [ ] if no title in frontmatter, and first non-blank line of markdown contains a heading then that heading becomes the title
  - [ ] TODO: may need to strip markdown formatting e.g. if italic, bold, links etc 
- [ ] if no description, the first paragraph of the document (after any title) becomes description (stripped of markdown formatting)

## Tasks

- [x] Resolve empty titles in contentlayer (~1h)  **✅ 2023-02-24**
  - [x] use first h1 heading (if exists)
  - [x] strip markdown formatting
  - [x] handle repeating titles ie. remove first markdown heading if title is displayed (~1h) **✅ 2023-02-26**
- [x] Resolve empty descriptions in contentlayer (~3h) **✅ 2023-02-24**
  - [x] use paragraph/text
  - [x] strip markdown formatting: use https://github.com/remarkjs/strip-markdown
  - [x] strip mdx formatting (commented lines, import statements, ... ?) **using regex**

**Comment by rufuspollock** [comment]
I think this is super convenient actually. It reduces repeating oneself (i.e. don't have to have frontmatter and content in the page) and improves SEO and blog functionality (e.g. having excerpt) immediately.

**Comment by khalilcodes** [comment]
@rufuspollock cc/ @olayway 

> NB: should we have description and excerpt be different?

are we going with excerpt as an additional field or using description ?

**Comment by rufuspollock** [comment]
@khalilcodes use description. Note we only do this extraction if description not already set in frontmatter (ditto for title etc).

**Comment by rufuspollock** [comment]
@khalilcodes before starting work can you update issue description with acceptance and tasks and estimate. (note i've done acceptance so more reviewing that).
