### ISSUE TITLE
Upgrade old nextjs-tailwind-mdx app to use contentlayer

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#3]
Currently using old-style explicit mdx loading. We want to use contentlayerdev now.

## Acceptance

* [x] contentlayer implemented **Done in `templates/default`**
  * [x] one standard type with no required fields **Done with one optional field `title`**
  * [x] used by `[...slug].js` **Done**
* [x] BONUS: content directory comes from siteConfig.js as single string or array (with brief note on what it is) **Done**

## Tasks

Can copy/paste from previous efforts e.g. https://github.com/life-itself/web3/blob/main/site/contentlayer.config.ts

**Comment by rufuspollock** [comment]
First pass done by @khalilcodes in https://github.com/flowershow/flowershow/commit/3ad675158d4d36c848a7e92643425f9543f70609
