### ISSUE TITLE
Main page title variations (with typed.js?)

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#307]
Currently main title is focused on "Obsidian" just because we had to pick one item at start:

> Publish your Obsidian notes, beautifully.

Suggest we could vary this e.g.:

- Publish your markdown notes, beautifully.
- Publish your [markdown] docs, beautifully.
- Publish your digital garden, beautifully.
- Publish your second brain, beautifully.

Other thoughts

- do we also try out varying "beautifully". Key aspects are: beautiful/elegant, easy, fast e.g. "Publish your digital garden easily and elegantly"

## Acceptance

- [ ] agreed list of variations
- [ ] cycle through these on the main page

## Tasks

- [ ] create list of options
- [ ] implement - suggest we use: https://github.com/mattboldt/typed.js/

**Comment by khalilcodes** [comment]
@rufuspollock I propose having it this way ... 

1. Publish your markdown notes, beautifully."
2. Publish your digital garden, easily.
3. Publish your second brain, elegantly.

Based on PR #401 I think beautifully should be varied as well.

**Comment by rufuspollock** [comment]
@olayway i let you call this one! We can always change later.
