### ISSUE TITLE
Google Analytics improvements

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#31]
Already have this roughly working. However one issue seems to be that it is tracking page titles rather than page urls at least on evidence of web3 site (? to be confirmed)

## Acceptance

* [x] Setup
  * [x] Tracking page urls (instead of or as well as page titles) **✅2022-07-22 INVALID - actually tracking page urls. Just that page names show by default. See screenshost just below showing the ability to select page urls in GA**
* [x] Documented
* [x] Deployed on flowershop.app **✅2022-07-21 and tested it worked 2022-07-22**

<img width="345" alt="image" src="https://user-images.githubusercontent.com/180658/180433999-4863ce68-5059-4ac9-9e3a-86bf88402b01.png">

## Tasks

* [x] Get code
* [x] Add to config
* [x] Deploy
* [x] Test

**Comment by rufuspollock** [comment]
FIXED. Deployed and working and nothing to fix in the setup.
