### ISSUE TITLE
[epic] Monorepo finalization

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#327]
Final refactor to a monorepo setup so that we can release more reliably, upgrades are easier, development is faster (e.g. updating remark plugin does not require multiple pull requests)

Questions:

- [x] what about CI tests for each package e.g. remark-wiki-link-plus (we start needing to filter on path changes or we run all tests all the time?)

## Job Stories

When developing flowershow i want all the key packages in one repo so that changes and releases are easier tyo make

When installing flowershow template (and modifying it) i want as clean a template as possible so that it is easy to make changes

When upgrading flowershow template being used as a full nextjs template (in ejected mode) I want to have as much of the dependencies in a separate package so that upgrading is easy

## Acceptance

- [x] remark plugins are in flowershow #303
  - [x] with a deprecation notice and archiving on current repo **deprecated on 01/12/2023**
- [x] "flowershow" or similar package for flowershow library of components, functions etc #350
- [x] release process is documented and in/linked from the developer docs
- [x] Have separate project in our monorepo for our Flowershow website https://github.com/flowershow/flowershow/issues/325 **❌2022-11-25 WONTFIX as we already removed symlinks in repo and add them automatically on build**
- [x] figure out how to update local package-lock files **no need to do that, we don't use per-package package-lock files any more, only one top level pnpm-lock file**

## Tasks

- [x] move remark plugins in to the repo #303 
- [x] move components and lib stuff out of template as much as possible and make template dependent on `flowershow` package #350
- [x] Process for doing Releases (involving changeset) - https://github.com/flowershow/flowershow/issues/189
- [ ] ...

## Notes

```
packages
  # cli => flowershow
  flowershow
    cli
    components
  template => does this get published? @flowershow
    package.json
  remark-...
site
  ...
```

**Comment by olayway** [comment]
> what about CI tests for each package e.g. remark-wiki-link-plus (we start needing to filter on path changes or we run all tests all the time?)

@rufuspollock we don't need to do any of that. An Nx's CLI command - `nx affected` - will run a specified target (e.g. `test`) only for the projects affected by the changes in a given PR. In this case, we would use `nx affected --target=test`. We are already using it for our e2e tests - we only have one e2e CI workflow, which will run e2e tests for all, some, or none of the projects (depending on changes in the PR compared to the last commit on main with passing tests) that have `e2e` target defined.
