### ISSUE TITLE
Search functionality in flowershow.app website

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#34]
When on flowershow website i want to quickly search for information

## Acceptance

* [x] Search in navbar a la tailwindcss.com etc ✅ **PR #81**
* [x] Docs for this feature ✅ **done  [/docs/search](https://deploy-preview-81--spectacular-dragon-c1015c.netlify.app/docs/search)**
  * [x] user section explaining what search is and maybe short screenshot.
  * [x] admin section explaining how to configure (e.g. what fields need to be set where)

## Tasks

* [x] Register on algolia docsearch **✅2022-08-08 did this and have stuff for flowershow.app**
* [x] Implement Search component and use
* [x] Docs

**Comment by rufuspollock** [comment]
@olayway can we submit now to algolia docsearch as can take a bit of time to get accepted.

**Comment by rufuspollock** [comment]
@olayway i've taken care of submitting this so don't worry.

**Comment by khalilcodes** [comment]
@rufuspollock config requirements for implementing search in algolia - App ID, Api key, Index name.

This is how it looks as per current PR status - #78

**Comment by rufuspollock** [comment]
@olayway do you want to review this one? You also have the config info we need here - i'm not sure all of it can be public (?). If not we may need to pull some from env variables.

**Comment by rufuspollock** [comment]
@olayway i've gone ahead and reviewed quickly.

**Comment by olayway** [comment]
Done in PR #81
