### ISSUE TITLE
<= or >= in a markdown file breaks build (?)

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#343]
**💬2025-02-10: i think we want a docs page on this and #333 as people will run into this a lot. In the longer term we want a way to maybe fix this issue e.g. avoid all the JSX problems we regularly have ... especially in cloud**

I suspect that <= and >= or anything with `>` or `<` in markdown files can break the build based on my own experiences and e.g. #333.

## Tasks

- [ ] Document this issue and solutions in blog post

Future

- [ ] think about fixes (e.g. replacing <= or >= with their unicode representation as happens automatically in obsidian) 

Tech work (not important for now)

- [ ] do a quick test in flowershow.app or similar
- [ ] make a failing test

**Comment by olayway** [comment]
@rufuspollock I have already tested it as one of our users on discord had a similar issue with their content.
Here is a related section from MDX docs: https://mdxjs.com/docs/troubleshooting-mdx/#unexpected-character-at-expected-expect.
And here is a discord thread with the related conversation: https://discord.com/channels/1029670148824641576/1038924012111274026

**Comment by danymat** [comment]
Adding my two cents: it seems that it is related to some markdown parser. Why ? 
Putting the characters inside codeblocks fixes the issue. Putting a space between the character and a number fixes the issue too.

**Comment by olayway** [comment]
@danymat https://github.com/flowershow/flowershow/issues/333#issuecomment-1337091429 🙂

**Comment by rufuspollock** [comment]
I think this can be a piece of shaping that also becomes a blog post (at least in how to fix).

**Comment by olayway** [comment]
FIXED

Now any < and > that couldn't potentially be an opening or closing tags (so no letter) will be automatically escaped. So `<100`, `<=`, `=>`, `100>` etc will render correctly.

This means `<a, b>` will still throw an error but handling cases like this is more complex as `<a` could be a start of a valid tag. 

Test page with error: https://test.flowershow.app/errors/mdx-error-1
Test page with error prevented: https://test.flowershow.app/errors/mdx-escaped-1

Relevant section in debugging docs (also linked to in the error message) for cases not auto-corrected by us: https://flowershow.app/docs/debug-mdx-errors#unexpected-characterx-in-attribute-name
