### ISSUE TITLE
Latest updates post Dec 2022 no 1

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#347]
I want to keep track of when emails/blog posts should be done

## Acceptance
- [x] December first update email and blog post done **2022/12/08 Done**

## Tasks
- [x] December first email sent **2022/12/07 Done**
- [x] December first blog post done **2022/12/08 Done https://flowershow.app/blog/2022-12-08-updated-features**

**Comment by rufuspollock** [comment]
@PhilippeduPreez i suggest we create an issue each sprint. if you want we can can an epic / inbox issue which lists all of them and which has a template for the issue.
