### ISSUE TITLE
[Epic] Blog support

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#35]
What is a blog?

- [Technical] A page with set of posts usually shown in reverse order
- [User Needs] show news / updates. usually more polished or "featured" content (not so much a notebook)

Note: the functionality of a blog and a news section are pretty much identical from a technical perspective. So in everything we write here about blogs also can be used to implement news.

## Acceptance

- [x] Blog feature MVP designed **✅2022-11-18 see https://flowershow.app/meta/blog-design with job stories, design etc**
- [x] Blog v0.1 implemented #296 
  - [x] index page for blog at https://flowershow.app/blog
- [x] tutorial on blog for the feature #318 **✅2022-11-25 https://flowershow.app/docs/blog-tutorial**
- [x] Blog v0.2 (minor) #317 
- [x] Authors support #239 

## Tasks

- [x] Design #150 
- [x] Implementation #296

**Comment by olayway** [comment]
This may be useful: There is an option to specify Contentlayer document types for single files, rather than based on `filePathPattern`. You can do that by adding `type: [TypeName]` directly in the document frontmatter.

https://www.contentlayer.dev/docs/sources/files/mapping-document-types#explicitly-specifying-document-type

**Comment by rufuspollock** [comment]
Authors support was added ~1 month1 ago on Dec 12th

**Comment by rufuspollock** [comment]
FIXED. All done! See https://flowershow.app/docs/blog-tutorial - plus more features e.g. authors etc.
