### ISSUE TITLE
Move as much as possible from template app into a core flowershow library

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#350]
Move as much as possible of components and lib stuff into separate flowershow node library so that template app is cleaner and easier to upgrade.

See details / job stories in parent issue #327 

## Acceptance

- [ ] "flowershow" or similar package for flowershow library of components, functions etc **12/14/2022 (olayway): I'd go with `@flowershow/core`**
- [x] decide whether cli merges **12/14/2022 (olayway): I wouldn't merge it. See my notes in the analysis below.**

## Tasks

- [X] review what is in template app **12/14/2022 (olayway): review and migration analysis done below**
- [ ] move components **12/16/2022 50% done; some adjustments to components need to be done along the way as they are not really decoupled UI elements atm but e.g. import stuff themselves from config instead of receiving only the data they need as props**
- [ ] move library
- [ ] new tests in library (?)

### Structure of the repo after creating the core flowershow package

 (`=>` means "moved to")

- /packages

  - **/template**
    (3) (./config/siteConfig.js) => packages/core/config/default.js
    (4) (./layouts) => packages/core/layouts
    (5) (./lib) => packages/core/utils
    (6) (./scripts/search.mjs) => packages/core/utils
    (7) (./styles) => packages/core/styles

    - /components
      (1) (./*) => packages/flowershow/ui
      (2) (./search) => packages/flowershow/search

        - /custom --> [user-components]

    - /content --> [user-digital-garden]

    - /pages
      - [...slug].jsx
      - _all.jsx
      - _app.jsx

    - /public
      - /_flowershow
        All Flowershow related assets. This needs to stay here (?)
      - /assets -> [user-assets]

    - package.json
      ```
      {
        "name": "@flowershow/template",
        "version": "1.0.0",
        "dependencies": {
          "@flowershow/core": "workspace:*",
         ...other template dependencies
        }
      }
      ```

  - **/core**
    - /ui
      (1) all standalone components from packages/template/components

    - /search
      (2) all components from packages/template/components/search

    - /config
      (we could have different config files for different templates here in the future)
      - default.js
        (3) contents of packages/template/config/siteConfig.js

    - /layouts
      (4) all components from packages/template/layouts

    - /utils
      (5) all files from packages/template/lib
      (6) file packages/template/scripts/search.mjs

    - /styles
      (7) all css files from packages/template/styles

    - package.json
      ```
      {
        "name": "@flowershow/core",
        "version": "1.0.0",
        "exports": {
            "./*": "./*",
            "./ui/*": "./ui/*",
            "./search/*": "./search/*",
            "./config/*": "./config/*",
            "./layouts/*": "./layouts/*",
            "./utils/*": "./utils/*",
            "./styles/*": "./styles/*"
        }
      }
      ```

  - **/cli**
  - **/remark-wiki-link**
  - **/remark-callout**
  - **/remark-embed**

### Do we merge the CLI with core Flowershow package?

- it means our `flowershow` package would be a cli-library combo, which is a bit weird and I wouldn't do that,
- when using the `flowershow`'s CLI part users would install unneeded dependencies of components, layouts etc. and on the other hand when adding `flowershow` as a dependency of templates unneeded dependencies of the CLI would have to be installed
- not really sure what's the benefit anyway

### Notes

- if we're going to publish the template to npm, `workspace:*` range protocol will be automatically converted to the latest version of `@flowershow/core`
- otherwise, if we keep copying the repo with degit we can replace it in the CLI with `latest`
  - this should also work without using `workspace:` protocol if there is a local version that satisfies the version range in the package json, so this would solve the problem

**Comment by olayway** [comment]
@rufuspollock can you please take a look at the above analysis and let me know if this looks about right to you?

**Comment by rufuspollock** [comment]
@olayway this looks great. Let's go for it 👏👏

> Do we merge the CLI with core Flowershow package?

I agree with your analysis. And we can have core app in npm as `@flowershow/core` (or similar)
