### ISSUE TITLE
Use named fonts and colors in default theme (and style guide for developers re this)

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#351]
When developing or customizing the default theme I want to to use standard named fonts and colors so that it is easier to change the theme coherently going forward

We currently tend to implement ad-hoc styling e.g. here is a snippet of Avatar.jsx

```
<div className="ml-3">
  <p className="text-sm font-medium text-black dark:text-white">
    {name}
  </p>
</div>
```

Should be like:

```
<div className="ml-3">
  <p className="text-sm font-medium text-primary dark:text-primary-dark">
    {name}
  </p>
</div>
```

We should be using standard named colors from tailwind.config.js so that

- it is easy for us to maintain consistency
- it is easy to for a user to systematically change colors across the whole site 

Our default theme does its styling for fonts using font-sans and font-serif. For colors people just add colors ad-hoc as they want. This means that making consistent changes to the theme either for developers or users meaning getting into the templates and components themselves which is painful and error-prone.

## Acceptance

- [x] using named semantic fonts for key font areas **✅ Done in PR https://github.com/flowershow/flowershow/pull/361**
- [x] using named semantic colors for key color areas **✅ Done in PR https://github.com/flowershow/flowershow/pull/362**
- [ ] style guide for this **✅2022-12-20 https://flowershow.app/docs/contributors#styling-and-tailwind**

## Tasks

- [x] Analyse how we implement in config
- [x] Add semantic items **✅ 2022-12-15**
- [x] Refactor existing templates and components to use these semantic labels **✅ 2022-12-15**
- [x] Add a note to developer docs to this (style guide?) **✅2022-12-20 https://flowershow.app/docs/contributors#styling-and-tailwind**

### Research

See https://tailwindcss.com/docs/font-family#customizing-your-theme and https://tailwindcss.com/docs/customizing-colors#using-the-default-colors

❗ complication: we use typography to do our default styling. However, we can customize key parts relatively easily https://tailwindcss.com/docs/typography-plugin#element-modifiers

eg. for headings we can do (in templates)

```
<article class="prose prose-img:rounded-xl prose-headings:underline prose-a:color-primary">
  {{ markdown }}
</article>
```

### Design

What areas do we want to customize by default? What's the KISS answer?

- fonts:
  - default font: defaults to font-sans though you can change this. See https://tailwindcss.com/docs/font-family#customizing-the-default-font
    - however changing this in [typography is painful as we have to change all the block level selectors](https://tailwindcss.com/docs/typography-plugin#element-modifiers). => maybe easiest is to set font-sans
  - body: default font (font-sans)
  - headings: make these customizable - relatively easy to do
     - typography is main focus plus recommend usage in style guide
  - navbar??: just follow default
  - footer just uses body and headings as usual
- colors: (all of these for dark/light)
  - background
  - primary
  - secondary
  - ...

Implementation in tailwind.config.js is something like this:

(note we want to still use tailwind default palette if we can in our default them)

```
module.exports = {
  theme: {
    fontFamily: {
      'sans': ['ui-sans-serif', 'system-ui', ...], # changes default and body font
      'serif': ['ui-serif', 'Georgia', ...],
      'mono': ['ui-monospace', 'SFMono-Regular', ...],
      'headings': ['Oswald', ...],
    }
  },
  colors: {
    background: {
      DEFAULT: colors.black,
      dark
   },
   primary: {
     DEFAULT: ...
     dark: 
   },
   ...			
}
```

**Comment by khalilcodes** [comment]
@rufuspollock adding the semantic items in `tailwind.config.js` and refactoring components to use them makes things fairly simple in changing the fonts and colors of the site.

*some questions*:
1. although adding this configuration in `config.js` is possible, the user would still need to add the imports for fonts in `styles/global.css` meaning they still have to dig in to `.flowershow` folder.
2. > Add a note to developer docs to this (style guide?)

    wouldn't this task be a modification in #345 ?

**Comment by rufuspollock** [comment]
@khalilcodes we should not do anything here in config.js - the user should edit tailwind.config.js - and `styles/globals.css`. BTW i don't think setting custom fonts is part of this - that work is separate and part of #292 

> wouldn't this task be a modification in https://github.com/flowershow/flowershow/pull/345 ?

No, these two tasks are quite distinct - though obviously related. This task is about refactoring the current default them to use named colors and fonts from tailwind.config.js. #292 and #345 are then about explaining to users how to customize the fonts and colors by changing the named values we have added here.

**Comment by rufuspollock** [comment]
@khalilcodes when do you think you'll get the PR in for this to review. (for future ref, it would have been great to have a first part of this pushed e.g. the fonts) so i could quickly review - and then we move on to the more complex colors part). That way we ensure we are on the same page. 😄

**Comment by rufuspollock** [comment]
@khalilcodes i'm still not sure we apply font headings font to the prose stuff. Can you confirm we are doing that?

**Comment by rufuspollock** [comment]
> @khalilcodes i'm still not sure we apply font headings font to the prose stuff. Can you confirm we are doing that?

Ans: we are doing in the docs layout atm. Up to you to use this wherever you need.

**Comment by rufuspollock** [comment]
FIXED. See acceptance. Have added named colors and fonts, using them and have a short docs on this.
