### ISSUE TITLE
Backlog grooming 2022-11-25

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#353]
Backlog grooming.

## Tasks

- [x] Remove analysis label (merge to research) **✅2022-11-25**
- [x] Close https://github.com/flowershow/flowershow/issues/114 **✅2022-11-25**
  - [x] update [[meta/design-cli]] with what we did (could ola do this?) - does it matter to update this? not really. **✅2022-11-25 - updated it**
- [x] Update high level [[meta/plan]] **✅2022-11-25 - partial**
  - [x] make sure key items are issues in roadmap board? (as that is main overview now) **✅2022-11-25**
- [x] Review all unprocessed backlog https://github.com/orgs/flowershow/projects/1/views/15

Questions

- [x] Get rid of "meta" section and merge with notes? **❌2022-12-10 👍 but someday maybe**

**Comment by rufuspollock** [comment]
FIXED. All tasks done.
