### ISSUE TITLE
Remove test folder in site/content

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#354]
All tests should be in template-e2e rather than in site/content.

## Acceptance

- [x] `site/content/test` has gone
- [x] any relevant content moved to other locations **`links-t-headings` covered in minimal reproduction repo created for contentlayer team: https://github.com/olayway/next-contentlayer-example; pages related to case sensitivity testing moved to `template-e2e` fixture content folder in case we want to write some tests for it in the future**

## Tasks

- [x] analyse what is in `site/content/test`
- [x] move it elsewhere

## Notes

Current content of `site/content/test`

```
├── Test
│   └── Page.md
├── case-sensitive-wikilinks.md
├── components-import.md
└── links-to-headings.md
```

**Comment by olayway** [comment]
Done.

**Comment by rufuspollock** [comment]
@olayway also see a bunch of test components in https://github.com/flowershow/flowershow/tree/main/site/components - can they also go?
