### ISSUE TITLE
Sitemap generation

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#355]
When building my site I want to generate a sitemap so that search engines pick up on all my site pages

## Acceptance

- [ ] Sitemap is generated with all pages
- [ ] Should not list "private" pages or similar

## Tasks

- [ ] Brainstorm an implementation
  - [ ] What is a sitemap
  - [ ] Look at how pliny does this - https://github.com/timlrx/pliny (note a bug https://github.com/timlrx/pliny/pull/83)
  - [ ] What nextjs libraries / approaches for this

## Notes

Approach analysis:

* nextjs docs has an implementation of adding a sitemap to pages `pages/sitemap.xml.js` which has a generate function. This uses `getServerSideProps` but I thiink this can test it out with `getStaticProps` too.
  * https://nextjs.org/learn/seo/crawling-and-indexing/xml-sitemaps
* pliny's approach is running a post build script that generates a sitemap in `/public` similar to how we have for search.json
  * also uses a globby package
  * vercel has a repo with similar implementation - https://github.com/vercel/next.js/tree/canary/examples/with-sitemap
* next-sitemap - https://github.com/iamvishnusankar/next-sitemap
  * config file in template - `next-sitemap.config.js`
  * add post build script in `package.json` - `"postbuild": "next-sitemap"`

**Comment by olayway** [comment]
@khalilcodes as we talked, please write an analysis as per the tasks above before implementing. Thanks!

**Comment by khalilcodes** [comment]
@olayway added some approaches in description notes.

**Comment by olayway** [comment]
Thank you @khalilcodes, I'll take a look today!

**Comment by rufuspollock** [comment]
@khalilcodes my 2c is i'd recommend following pliny i think (it sounds like it is based on nextjs example).
