### ISSUE TITLE
Link previews on hover

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#36]
Distinguish external and internal link previews. For now focus on internal links.

Note we already implemented this in web3.lifeitself.org so i think a question of porting this over - see https://github.com/life-itself/web3/issues/150 and PR https://github.com/life-itself/web3/pull/162

## Acceptance

- [ ] When i hover over an (internal) link i get a preview of the contents (e.g. first X words) on that page
  - [ ] (also maybe the featured image if there is one?)

Example from https://web3.lifeitself.org/guide

<img width="691" alt="image" src="https://user-images.githubusercontent.com/180658/199662363-693ad2f5-9b32-4d09-a310-2186ee51bbe2.png">

## Tasks

- [x] Research and estimate this **✅ 2022-12-13 Porting over from web3**
- [x] Create docs with guide to toggle off **✅ 2022-12-14**
- [x] Create the tooltip component **✅ 2022-12-14**
  - [x] modify to parse the content body **using https://github.com/markedjs/marked**
  - [x] modify to use frontmatter image in preview if available
- [x] Add option to disable in `config.js` **✅ 2022-12-14**

**Comment by khalilcodes** [comment]
@olayway do we want this to be optional in config ?

**Comment by rufuspollock** [comment]
@khalilcodes great work.

> 
@olayway do we want this to be optional in config ?

IMO we could just make this default behaviour for now and not worry about making it optional. But, if that is very cheap to do, then do it.

> modify to parse the content body using [markedjs/marked](https://github.com/markedjs/marked)

Out of interest why are we using marked when we already have remark? does that mean we now have a bundle dependency on two markdown parsers?

@khalilcodes btw where's the estimate for this - i don't see any time estimate.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/180658/207704563-f2ee4747-70ae-42c2-ba00-3af4eca3950f.png">

**Comment by khalilcodes** [comment]
@rufuspollock 

> Out of interest why are we using marked when we already have remark? does that mean we now have a bundle dependency on two markdown parsers?

we would have to add remark-parse and unified and extract the required content like we do in web3. I used marked instead cause it's client side, but can be replaced.

**Comment by rufuspollock** [comment]
@khalilcodes is this done? can we update acceptance and close?

**Comment by rufuspollock** [comment]
@khalilcodes is ready to go and is opening a PR.

**Comment by rufuspollock** [comment]
FIXED. Copying from #382 

### Summary

This PR adds the feature to show previews for internal pages on hovering over it's link. This feature can also be disabled by setting `showLinkPreviews` property to false in `config.js` (enabled by default)

### Changes

* Add new packages:
  * core: 
    - `@floating-ui/react-dom`
    - `@floating-ui/react-dom-interactions`
    - `framer-motion`
  * template: `@tailwindcss/line-clamp`
* Add new Tooltip Component in core
* Modify CustomLink component in core
* Modify props for `CustomLink in template/pages/[[...slug]].jsx`
* Add tooltip styles in `template/styles/global.css`
* Add tailwind plugin in `template/tailwind.config.cjs`
* pnpm-lock updated
* update documentation in [docs/link-previews](https://deploy-preview-382--spectacular-dragon-c1015c.netlify.app/docs/link-previews)

### Screenshot preview

<img width="846" alt="Screen Shot 2023-01-18" src="https://user-images.githubusercontent.com/42637597/213283946-c7b0c959-ac8a-4aa2-935a-14053ca24d67.png">
