### ISSUE TITLE
Tutorial for non-technical users on how to edit a markdown and Flowershow site

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#363]
I am a non technical user new to markdown, I need a tutorial explaining how I can make changes to my flowershow website

## Acceptance
- [ ] Tutorial shows clear steps with screenshots of how and where to add and edit markdown files

## Tasks

- [ ] live recorded session with yoana/monika to e.g. edit datopian.com
- [ ] analyse that and identify next steps

**Comment by rufuspollock** [comment]
@PhilippeduPreez i would do the live recorded session with yoana/monika first here and then we analyse that.
