### ISSUE TITLE
[epic] Flowershow website v0.1 (landing page)

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#4]
Simple, elegant landing page that explains what the product is and provides a way to get started (or signup if that is not ready) so that we can start sharing/testing with people and get early interest

## Acceptance

* [ ] Landing page website in site folder **🚧2022-06-26 in progress atm.**
  * [x] uses default template from `templates/default`
  * [x] Hero section
  * [ ] CTA in hero section **✅ 2022-07-26 #72**
  * [x] Link to github in navbar (new config option like we had on web3??) **✅2022-07-19 working**
* [x] Site deployed **✅2022-06-26 working on netlify at https://flowershow.app**
* [ ] Add an “Alpha” button to navbar like contentlayer has **✅ 2022-07-26 #73**

## Tasks

* [ ] Content
* [x] Implement theme (focus on landing page)  #23 
  * [x] Depends on #8 
* [x] CTA: Get updates - with Subtext: Get short updates when we release new features (like web3 but shorter) **✅ 2022-07-26 #72**

### Content

* [x] brainstorm ideas e.g. value props, tagline, description **✅2022-06-22 see copy draft doc**
* [x] distill **🚧2022-06-22 50%??**
* [x] refine into slides **🚧2022-07-08 [slides in gdocs](https://docs.google.com/presentation/d/1-x7sOBmmJJZF31xqWa-ocqW0QP7VpGJFkUlth8drBYQ/edit)**
  * [x] Hero/Summary
    * [x] Header
    * [x] Subheader
    * [x] CTA

### CTA

Options:

1. 2 buttons
2. Sign up form

* “Get Started” => sign up for flowershow form
* Get updates
  * Subtext: Get short updates when we release new features
* Sign Up
  * Subtext: sign up to get notified when it’s ready

#### Option 1) 2 buttons: "Get Started" and "Learn more". 

"Get started" should lead to a form to be notified when we launch properly (brief blurb about "launching soon.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/180658/179705436-689295e7-ea40-417f-8143-74f28102b068.png">

#### Option 2) Sign up to get notified email

Like on web3 or here on tailwindui

<img width="667" alt="image" src="https://user-images.githubusercontent.com/180658/179704774-6442e762-50da-438b-8678-9293d3c67a9a.png">

### Setup

* [x] Initial setup **✅2022-06-26 most of this in #1 as part of dogfooding so see there**
* [x] Deployment

### Deployment

* [x] Deploy e.g. on cloudflare pages **❌2022-06-26 running into issues with root directory and the ability to set content directory. Builds fine using root directory as `templates/default` for the default template but using the `FLOWERSHOW_CONTENT` config to point to the content directory is not working**
* [x] OK so the issue is that my guess is that cloudflare pages limits access of the build to stuff outside of the root directory in some way **✅2022-06-26 ultimately realized no real way to do this with cloudflare pages other than having everything inside the root / build directory which doesn't really work for our use case or our planned use case for users. However, netlify does allow symlinking so going with that**
  * See e.g. https://community.cloudflare.com/t/access-outside-of-root-dir-in-cloudflare-pages/386536 and https://community.cloudflare.com/t/cloudflare-pages-root-directory/329038 plus general security considerations - though note that netlify and vercel don't do this (and no clear reason why you couldn't just limit access to based on git repo you have cloned).
  * Thought we could work around this by changing root directory to base directory and then having build command of `cd templates/default && npm run build && npm run export` however this does not work b/c cloudflare pages runs e.g. npm install in the root directory ...
* => we have to go the symlink root whereby we symlink content folder into the nextjs template **LATER: on reflection no reason this would work any better. cloudflare pages doesn't allow access outside root folder whether symlink or otherwise. That said i think this symlinking actually makes sense given the config file location issues in #7**
  * if so, do we a) just symlink content back into templates/default *or* make an actual copy (rather than symlink) of templates/default into site/.flowershow
  * KISS => just symlink into templates/default for now
    * However, note this may make installing from that template behave weirdly e.g. there will be loads of stuff in content. 🤔
    * For the record: tried a semi-hack where still `.flowershow/templates/default` but made it a real folder and then symlinked subcontent but that ran into loads of issues which i think relate to nextjs not allowing imports from outside root directory see e.g. https://github.com/vercel/next.js/pull/22867 + https://github.com/vercel/next.js/issues/706
* [x] Deploy on netlify **✅2022-06-26 working after restricting node version - see comment below.**

**Comment by rufuspollock** [comment]
OK, so tried building on netlify too. netlify has no issues with symlinks and contentlayer generated correct files. However, ran into build failure with:

```
import allPages from './Page/_index.json' assert { type: 'json' }
```

Context:

```
9:44:14 PM:  Failed to compile.
9:44:14 PM: 
9:44:14 PM: ./.contentlayer/generated/index.mjs
9:44:14 PM: Error: error: Expected ';', got 'assert'
9:44:14 PM:   |
9:44:14 PM: 7 | import allPages from './Page/_index.json' assert { type: 'json' }
9:44:14 PM:   |                                           ^^^^^^
9:44:14 PM: Caused by:
9:44:14 PM:     0: failed to process js file
9:44:14 PM:     1: Syntax Error
9:44:14 PM: Import trace for requested module:
9:44:14 PM: ./pages/[[...slug]].js
9:44:14 PM: > Build failed because of webpack errors
```

Checking around i find that contentlayer introduced an optimization in https://github.com/contentlayerdev/contentlayer/releases/tag/v0.2.1

> assert { type: 'json' } is required when importing JSON files using Node v16.14 or higher. However, it is invalid syntax when using an earlier version of Node.
>
> These assertions are now automatically added to generated .mjs files based on the current version of Node. https://github.com/contentlayerdev/contentlayer/issues/153

However, setting NODE_VERSION in netlify to 16.14 or even 17 did not resolve this error! 🤔

**Comment by rufuspollock** [comment]
Updated home page with main benefits.

**Comment by rufuspollock** [comment]
@olayway would welcome your thoughts on the CTA approach (see CTA section i've created with 2 options).

**Comment by rufuspollock** [comment]
We have decision on CTA and will implement today.

**Comment by olayway** [comment]
@rufuspollock I've created a basic form in the hero section and a success page. Here is the draft of the PR -> #72. 
This is a draft because there is one issue I've encountered: "405 Method not allowed" after submitting the form locally. If the changes look good to you, maybe we could merge them and test if it works on the deployed version?

**Comment by rufuspollock** [comment]
@olayway merged and we can now test.

**Comment by rufuspollock** [comment]
FIXED. **✅2022-07-28 All DONE**

![image](https://user-images.githubusercontent.com/180658/181478918-f0d90f5e-44d0-40ac-b3fe-76e8b15f5c11.png)
