### ISSUE TITLE
Background and text not changing colors with tailwind config

### ISSUE THREAD

**Issue by PhilippeduPreez** [flowershow/flowershow#400]
Navbar Background, headings, emphasized text, code not changing colors with tailwind config changes

## Acceptance
- [x] Background display fixed
- [x] Headings display fixed

## Tasks
- [x] Fix Background display of Navbar in `core/Nav`
- [x] Find out where heading colors are inherited from **can add `prose-headings:text-primary to layouts**
- [x] Fix heading colors

## Notes
Changing text and background color leads to this:

![image](https://user-images.githubusercontent.com/44789132/214533883-865602d3-a220-4135-b619-72296ca2007f.png)

Navbar is an easy fix, but I assume we also want headings etc. to be displayed in the same color as the paragraphs?
