### ISSUE TITLE
Discord polls (what tutorials people need)

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#413]
Make a poll for which tutorial users want next with 2 options so we can get some user engagement as well as figure out the users' needs

## Acceptance
- [x] Make poll on discord **2023/02/08 Link to poll [here](https://discord.com/channels/1029670148824641576/1029670149470556172/1072808365501206528)**
- [x] Wait for results after ~ day and make issue for this if we don't have one already **Custom page types and layouts**

## Tasks
- [x] Decide on poll options **2023/02/08 Customize nav bar and footer OR
Custom page types and layouts**
- [x] Make poll on discord **2023/02/08 Link to poll [here](https://discord.com/channels/1029670148824641576/1029670149470556172/1072808365501206528)**
- [x] Wait for results after ~ day and make issue for this if we don't have one already **Custom page types and layouts**

**Comment by PhilippeduPreez** [comment]
Link to poll [here](https://discord.com/channels/1029670148824641576/1029670149470556172/1072808365501206528)

**Comment by rufuspollock** [comment]
@PhilippeduPreez could you put detail of what was in the poll and i think we close this when we actually have some results (summarized here).

**Comment by olayway** [comment]
Done. 

<img width="919" alt="image" src="https://user-images.githubusercontent.com/52197250/218736761-5506eee2-abe2-4334-8fb4-135c96422bc7.png">
