### ISSUE TITLE
Support for `date` frontmatter field as default date field rather than `created`

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#445]
`date` frontmatter field is default date field rather than `created`

See discussion #416

## Acceptance

- [x] `date` frontmatter field support added
- [x] `created` frontmatter filed supported as well for backwards compatibility

## Tasks
- [x] add `date` computed field in contentlayer's config file
  - [x] takes frontmatter's `date` field value if present
  - [x] otherwise uses frontmatter's `created` field value

**Comment by rufuspollock** [comment]
@olayway i think we need a bit more detail on acceptance. e.g. what does support mean. i imagine here it means it is used on blogs and other places where we display a "published" date.
