### ISSUE TITLE
Enable/disable hover-over tooltips per page

### ISSUE THREAD

**Issue by PhilippeduPreez** [flowershow/flowershow#455]
I want the option to enable/disable hover-over tooltips per page, so I can have more creative freedom on how my pages are displayed

## Acceptance
- [x] hover-over tooltips can be enabled/disabled per page **added showLinkPreview frontmatter field**
- [x] remove hover-over tooltip from flowershow's home page and index pages **Done**
- [x] add change to docs **https://flowershow.app/docs/link-previews**

## Tasks
- [x] hover-over tooltips can be enabled/disabled per page
- [x] remove hover-over tooltip from flowershow's home page and index pages
- [x] add change to docs

**Comment by rufuspollock** [comment]
@PhilippeduPreez i don't think this is a feature i wanted. Who requested this feature?

**Comment by olayway** [comment]
@rufuspollock I requested this feature as I thought this is an extremely easy, low-effort, and requires almost no-code thing to add. It's not even a feature... We can enable/disable all the other functionalities per-page basis so this also seemed natural that we would want to have it. Where did this idea come from: I was reviewing our home page looking for possible improvements while writing acceptance criteria to the task you opened: #410

**Comment by rufuspollock** [comment]
@olayway thanks for clarification. my concern is that whilst trivial it inevitably increases the maintainability surface for what seems like quite a minor benefit (i struggle generally to imagine many use cases where i want to turn off link previews on a a per page basis). I guess we can merge for now 😄
