### ISSUE TITLE
`remark-wiki-link` package refactoring

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#464]
## Acceptance
- [x] supports all of the formats below
  - [x] [[Wiki Link]]   # relative wiki link
  - [x] [[Wiki Link|Alias]]   # wiki link with alias
  - [x] [[some/folder/Wiki Link]] # obsidian absolute paths
  - [x] [[Wiki Link]] # obsidian shortened paths
  - [x] ![[...]]  # for images and other embeds **🚧 some small bug in the syntax extension, but I'm too tired to spot it 😅**
- [x] has extensive tests for
  - [x] `syntax` extension
  - [x] `html` extension
  - ~[ ] `fromMardown` extension~ **removed, not needed**  
  - ~[ ] `toMarkdown` extension~ **removed, not needed**  
  - [x] `remark-wiki-link` plugin itself
- [x] replace `mocha` with `jest` as it's used in all other projects
- [x] refactor to TS

## Tasks
- [x] understand how the plugin and all the micromark extensions work 
- [ ] ...

**Comment by olayway** [comment]
@rufuspollock I've created a draft of the PR for this. It's almost done, just need to debug image embeds.

<img width="870" alt="image" src="https://user-images.githubusercontent.com/52197250/228098570-09c27cba-856a-4eca-8566-9180f1bca4d1.png">

**Comment by rufuspollock** [comment]
@olayway great job - well done.
