### ISSUE TITLE
Best practice for doing forms and newsletters on Flowershow

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#480]
When creating a website a standard to add a signup form e.g. for registrations so that i can easily allow people to signup to my course / event / newsletter etc

When creating a webssite I want to have a newsletter (? what does this mean) so that people can keep up to date with what i am doing

## Acceptance

- [ ] Documentation of at least one easy / standard approach we use (e.g. sendinblue)
- [ ] Review pliny approach and what they support
- [ ] 🏆 comparison of various options

## Tasks

- [ ] ...

### Discussed in https://github.com/flowershow/flowershow/discussions/469

<div type='discussions-op-text'>

<sup>Originally posted by **rufuspollock** March 30, 2023</sup>
What are the options for forms for Flowershow sites?

Would love some documentation about this (later we can migrate to docs) ... so that we know best practice (and options) for doing forms going forward

- [ ] Using netlify forms
- [ ] Using sendinblue
- [ ] Using jamstack forms services e.g. getbasin etc
- [ ] ...

Things to answer

- [ ] What have people tried out
- [ ] What are pros / cons?
- [ ]  What is recommended approach?
- [ ] Howtos for specific cases

@khalilcodes @olayway can you share your notes / experiences ...</div>

**Comment by olayway** [comment]
@rufuspollock  I'd say creating a Newsletter component is a no-go (at least for now). See my comment here: https://github.com/flowershow/flowershow/issues/781#issuecomment-2909247111

I've submitted a PR draft with docs on adding newsletter form embeds here https://github.com/flowershow/flowershow/issues/781#issuecomment-2909247111 (not final version). It proposes the use of 
iframes for simple Iframe forms and  `CustomHtml` component in more complex form embeds that require multiple tags, including inline scripts, styles etc. We could make it "safer" by wrapping the custom html in a sandboxed iframe theoretically if I'm correct.

**Comment by olayway** [comment]
@rufuspollock ^

**Comment by olayway** [comment]
FIXED https://github.com/flowershow/flowershow-app/blob/main/blog/how-to-add-forms.md
