### ISSUE TITLE
SEO support

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#57]
When creating a site I want to set description, image, title set on page (and have default values) so that have good SEO 

There are really two parts to this:

- Site-wide SEO: common and/or default SEO values for the whole site (and especially the front page)
- Per-page SEO: SEO per page that overrides default SEO values. These would derive from frontmatter and/or be calculated e.g. title from markdown first heading etc (nb: any work to calculate title etc is out of scope for this issue - this issue can assume those values are available)

**Priority right now is the first**

We can follow the work we did in web3 for this e.g. https://github.com/life-itself/web3/issues/114

## Acceptance

* [x] Can configure default SEO - full stack of next-seo options in config and these get used on every page (can get overriden) **✅2022-08-16 see https://flowershow.app/docs/seo and https://socialsharepreview.com/?url=https://flowershow.app**
  * [x] This SEO shows up on front page **✅2022-08-16 see https://socialsharepreview.com/?url=https://flowershow.app**
  * [x] SEO shows up on every other page where not explicitly overridden **✅2022-08-16 this works**
  * [x] Docs page explaining how to set and referencing options in next-seo **✅2022-08-16 https://flowershow.app/docs/seo**
* [x] Per page SEO values for title, description, image etc which come from frontmatter or elsewhere **🚧2022-08-16 done for title, description but not image yet. An example can be see on https://flowershow.app/docs/seo where title is different**
  <img width="500" alt="image" src="https://user-images.githubusercontent.com/180658/184887045-8ca0ad46-03e6-494a-b580-c7c65b4f8a40.png">

Proposed Default Next SEO (note other SEO values would get set from other config values e.g. title and description)

```
nextSeo: {
    openGraph: {
      images: [
        {
          url: "https://web3.lifeitself.us/img/home-page-screenshot-social-preview.png",
          alt: "",
          width: 1200,
          height: 627,
          type: "image/jpg",
        },
      ],
    },
    twitter: {
      handle: "@forlifeitself",
      site: "web3.lifeitself.us",
      cardType: "summary_large_image",
    },
  },
```

## Tasks

* [x] Create docs
* [x] ...

**Comment by rufuspollock** [comment]
This is high priority as we are about to start sharing on social media (at least for front page to have it).

**Comment by rufuspollock** [comment]
@khalilcodes to add image support as last item.

**Comment by olayway** [comment]
@rufuspollock, @khalilcodes I think this issue can be closed now?

**Comment by khalilcodes** [comment]
@olayway og:image was added on last merge and og:title to match site title is still wip ...

**Comment by olayway** [comment]
@khalilcodes a few things I've noticed:

https://github.com/flowershow/flowershow/blob/863f62f542d5fef1fd00599d2b156602695aa30f/templates/default/config/siteConfig.js#L3-L5

https://github.com/flowershow/flowershow/blob/863f62f542d5fef1fd00599d2b156602695aa30f/templates/default/pages/_app.js#L32-L37

1. I don't think it makes much sense to have `title` and `description` properties outside of `nextSeo` property. They are used for SEO only and are also listed as options of NextSeo package, so I'd keep them where other SEO config options are. Also, currently we're not really allowing users to just use `title` they set. Instead, `titleTemplate` of the following form is forced: `'%s | ' + siteConfig.title`
2. I'd move `titleTemplate` and `defaultTitle`, to `siteConfig.js` file.
3. Having done all the above, we'd end up with just this in our `_app.js` file:
```js 
 <DefaultSeo 
   {...siteConfig.nextSeo} 
 /> 
```

**Comment by olayway** [comment]
One more thing. I think we don't need this part in our `Layout.js` as we're setting all the SEO values in `MDX.js` file.

https://github.com/flowershow/flowershow/blob/863f62f542d5fef1fd00599d2b156602695aa30f/templates/default/components/Layout.js#L10-L12

**Comment by olayway** [comment]
Also, this line

`     ...config.nextSeo.openGraph `

 overwrites all per-page settings. So it's not possible to e.g. use another image for a single page.

https://github.com/flowershow/flowershow/blob/863f62f542d5fef1fd00599d2b156602695aa30f/templates/default/components/MDX.js#L20-L37

Default values are already set in `DefaultSeo` in `_app.js`, so I think this line is redundant whatsoever.

**Comment by khalilcodes** [comment]
Hey @olayway please review following points:

> 1. I don't think it makes much sense to have title and description properties outside of nextSeo property.

By this what I'm understanding is that our config should be as below ?
```js
const config = {
  nextSeo: {
    openGraph: {
      title: .... ,
      description: ... ,
    }
  }
}
```
It was proposed above in acceptance that the `title` and `description` values should get set from other config values.


> titleTemplate of the following form is forced: '%s | ' + siteConfig.title

Are we looking to keep the title like below instead ? (ie., no format)

<img width="350" alt="Screen Shot 2022-08-23 at 8 36 19 PM" src="https://user-images.githubusercontent.com/42637597/186228606-fdf496de-6235-4b08-8870-c86d62c9d5bd.png">


> One more thing. I think we don't need this part in our Layout.js ...
>
> Also, this line
> ...config.nextSeo.openGraph
> overwrites all per-page settings.

Well noticed and fixed 👍

**Comment by olayway** [comment]
> @olayway @khalilcodes i would keep these as we _could_ use these outside of SEO, at least the title would be used in the navbar by default i think if you hadn't set a logo or something. Description maybe not so much. That said, for now i think we could go this way - i actually think @olayway is right that we move this to the SEO and have a separate value (if we need it) for say the navbar.

Yup, I'd keep SEO-related stuff from other (e.g. presentation-related) stuff separate.

**Comment by olayway** [comment]
> Are we looking to keep the title like below instead ? (ie., no format)

@khalilcodes I just think that setting this title template should be optional and customizable in the config file. If we want to use " <title> | Flowershow " format for us, let's configure it in the config file so that people are aware where it comes from and can also adjust it to their needs. But they also should be able to just use a plain title they set (globally or per-page).

**Comment by olayway** [comment]
> Also, by not setting a default title, pages without frontmatter title would not show, for eg.

@khalilcodes, Sure thing. I was just saying we don't need `titleTemplate` and `defaultTitle` for that. Also, `defaultTitle` is basically used with `titleTemplate` only - as a fallback value in case `titleTemplate` evaluates to `undefined` (at least this is what I understand from the next-seo docs).

So, in order to set the default (i.e. globally-set) title for all pages you just need to do this:

```js
      <DefaultSeo
        title={siteConfig.title}
        description={siteConfig.description}
        {...siteConfig.nextSeo}
      />

```

or even better, if we move `title` and `description` to `nextSeo` property:

```js
      <DefaultSeo
        {...siteConfig.nextSeo}
      />

```

**Comment by olayway** [comment]
> > @olayway @khalilcodes i would keep these as we _could_ use these outside of SEO, at least the title would be used in the navbar by default i think if you hadn't set a logo or something. Description maybe not so much. That said, for now i think we could go this way - i actually think @olayway is right that we move this to the SEO and have a separate value (if we need it) for say the navbar.
> 
> Yup, I'd keep SEO-related stuff from other (e.g. presentation-related) stuff separate.

@khalilcodes, @rufuspollock  if you take a look at the next-seo doc's example of typical SEO settings, they even distinguish between ordinary `title` and `description` tags and OpenGraph's `title` and `description` for social sharing. I think atm we can use `title` and `description` values for both but just FYI. Maybe sometime in the future we could also make this distinction and for OpenGraph have frontmatter tags that start with `og:`, e.g. `og:title: Some OG Title` as it's not really complicated to implement.

**Comment by olayway** [comment]
> > I don't think it makes much sense to have title and description properties outside of nextSeo property. They are used for SEO only and are also listed as options of NextSeo package, so I'd keep them where other SEO config options are. Also, currently we're not allowing users to just use title they set. Instead, titleTemplate of the following form is forced: '%s | ' + siteConfig.title
> 
> @olayway @khalilcodes i would keep these as we _could_ use these outside of SEO, at least the title would be used in the navbar by default i think if you hadn't set a logo or something. Description maybe not so much. That said, for now i think we could go this way - i actually think @olayway is right that we move this to the SEO and have a separate value (if we need it) for say the navbar.
> 
> And btw @olayway **very good, thorough** comments.

@rufuspollock, @khalilcodes maybe the current `title` should be renamed to e.g. `name`, not to confuse it with SEO `title`. And like you said, Rufus, it could be used as a fallback value/alt value for logo image.

**Comment by khalilcodes** [comment]
@rufuspollock @olayway using a `title` field in `nextSeo` and not using the `defaultTitle` will lead to the following issue for pages without frontmatter titles or the homepage. This is because the `title` now is always defined.
<img width="289" alt="Screen Shot 2022-08-24 at 3 44 24 PM" src="https://user-images.githubusercontent.com/42637597/186419912-225837b2-e616-4105-9dbf-b5dcc4ca2cbe.png">

This is my suggestion for things to work correctly:
```js
// in config.js
const config = {
  title: "Flowershow"
  nextSeo: {
    titleTemplate: "%s | Flowershow",
    description: "....",
    ...
  }
}
```
```js
// in _app.js
<DefaultSeo defaultTitle={siteConfig.title} {...siteConfig.nextSeo} />
```
* Have a `titleTemplate` in config so users can modify or remove
* *NOT* have a `title` property inside **`config.nextSeo`** property
* Use `defaultTitle` in `_app.js`

Please review this so that I can close #123

**Comment by olayway** [comment]
Closing as done in #123
