### ISSUE TITLE
Testing v0.1

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#6]
Let's start testing our site asap with e2e tests both for local text and CI.

## Questions

* [x] do we use cypress or playwright? **any works, let's use playwright**

## Acceptance

* [x] One passing e2e tests **✅ 2022-06-27**
* [ ] CI setup (??) - this could be left to later if complex

## Tasks

* [x] Follow instructions here https://nextjs.org/docs/testing#playwright
* [ ] CI Setup - https://playwright.dev/docs/ci#ci-configurations

## Notes

Things to test

* [x] Root index page (from markdown) **✅ 2022-06-27**
* [ ] Adding a js page somewhere (and it still works with catch-all route)
* [ ] About page
* [x] nested index page etc **✅ 2022-06-27**

<img src="https://user-images.githubusercontent.com/42637597/175997147-62ba0879-5d69-4f4c-a6db-f68fc8e38512.png" height="250" />
