### ISSUE TITLE
Math syntax support

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#64]
Math support is very useful. We'll follow Obsidian who use mathjax (https://help.obsidian.md/How+to/Format+your+notes#Math).

Here's a guide to supporting this in markdown/mdx: https://mdxjs.com/guides/math/

Essence is to use two plugins https://github.com/remarkjs/remark-math/tree/main/packages/remark-math and https://github.com/remarkjs/remark-math/tree/main/packages/rehype-mathjax

## Acceptance

* [ ] Inline math like `$\sqrt{a^2 + b^2}$` works
* [ ] Block math works like the below
* [ ] Documentation on e.g. `/docs/math`

```
$$\begin{vmatrix}a & b\\
c & d
\end{vmatrix}=ad-bc$$
```

## Tasks

* [ ] Add the two plugins

**Comment by rufuspollock** [comment]
Low priority atm as we are not using it and no-one yet requesting it. Nice to have.

**Comment by rufuspollock** [comment]
@khalilcodes this seems so simple that's it worth doing now ...
