### ISSUE TITLE
Features / Roadmap section on frontpage

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#65]
Add a features list / roadmap (i.e. features we haven't yet done) to the front page.

Can start by copying what we have on https://flowershow.app/docs/roadmap into frontpage and adding feature we have done with links to the docs

Do the basic first ie. use markdown and just headings etc

Later we can do another iteration to make it fancy

## Acceptance

**✅ 2022-07-28 all done in PR #74**

* [ ] Features and Roadmap section ✅
* [ ] Some items in it (don't have to list everything) ✅
  * [ ]  links to docs pages where they exist ✅
  * [ ] use emojis for under construction / planned / done ✅

## Tasks

* [x] Add section
* [x] Add 3 existing features
* [x] Add 3 planned features
* [ ] Review
* [ ] Then do more
