### ISSUE TITLE
Tweet link in markdown shows a preview/embed

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#67]
See previous effort in web3 https://github.com/life-itself/web3/issues/150

Like we do with youtube ... #88 

## Acceptance

* [x] Pasting a twitter link in its own paragraph at line start results in embed e.g. pasting the following results in an embed/preview of the tweet
* [x] Docs page for this **added at `docs/social-previews`**

```
Blah, blah ...

https://twitter.com/rufuspollock/status/1524012242777395201

```

## Tasks
- [x] research and proposed solution with time estimate **Best option for now is similar implementation to web3 https://github.com/life-itself/web3/issues/150**
- [x] create a tweet embed component
    - with placeholder for loading and deleted/not found tweets **2023/02/13 Done**
- [x] add custom styles for proper tweet embed previews (dark mode) **Only adding this after we fix light/dark switch**
- [x] use component in links for parsing in markdown. **Using customlink**

## Notes

- Twitter embed api is fairly slow and so takes time to load. A placeholder has been added for better ux.
- On further research during development, the embeds (youtube, twitter, etc) load iframes with large htmls which affect the page load and SEO.
- Possible solutions to the above problems:
     -  fetch tweets and render component during build time. This requires getting a twitter api key and recreating custom twitter component that matches the look of the embed. (overwork but blazing fast. see [here](https://static-tweet.vercel.app/)).
     - create remark plugin for twitter embeds based on this [gatsby remark plugin](https://github.com/octahedroid/gatsby-remark-twitter/blob/master/index.js). Although still not sure if this would resolve tweet loading time.

## Analysis
- Fetch tweets and render component during build time not going to work now due to changes in twitter's api
- Embed plugin option not going to be efficient since scripts in the browser are needed
- Best option for now is similar implementation to web3 https://github.com/life-itself/web3/issues/150

**Comment by olayway** [comment]
@PhilippeduPreez let's extend our remark-embed plugin to handle twitter embeds as well

**Comment by PhilippeduPreez** [comment]
@olayway Twitter API usage is not free anymore, so twitter embeds (iframe) looks like the best solution and can be added in the existing remark-embed plugin
