### ISSUE TITLE
Standard Frontmatter

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#71]
When creating markdown pages I want to know about some standard frontmatter fields for common functionality e.g. title, date etc so that I can add them and get related functionality

Questions

* [ ] Does this issue include "computing" values for these where missing e.g. for title  and description

## Acceptance

* [ ] Document the following
  * [ ] title
  * [ ] date: publication date. would be used in a blog section
  * [ ] description: page description
  * [ ] image: image to use for the page for example in social preview, in blog post listings etc. TODO: what about setting image dimensions (?)
  * [ ] created: date *this* page in wiki was created (so more internal housekeeping)
  * [ ] aliases: obsidian field for aliasing pages
* [ ] Document how to access these from within a page (if that is possible) - cf #20 

Optional ... (to be decided if we use these - if we have them all the time we could have a standard layout for these pages)

* [ ] youtube
* [ ] podcast

## Tasks

* [ ] ...
