### ISSUE TITLE
Configurable layouts for pages

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#8]
Allow for (at least) 2 different layouts: a) "content/documentation" (classic markdown style) b) "landing" (or just "unstyled") which is pretty much a raw page with navbar and footer ie. unstyled

## Acceptance

* [x] can set `layout: {name}` in frontmatter of a markdown page and uses that layout from `components` (ignorecase is supported e.g. layout: abc` matches `layouts/Abc.jsx` **✅2022-06-28 in #15. Two layouts. @khalilcodes one question is whether case insensitive (not a big deal if not)**
* [x] One default one (maybe configurable??) that is used if not specified. Suggest docs is the default. **✅2022-06-28 docs is the the default**
* [x] Two layouts: `unstyled` and `docs` **✅2022-06-28 working**
* [x] Tests (at least "demo tests") **very basic tests. need something better if we can**

## Tasks

...

**Comment by rufuspollock** [comment]
@khalilcodes i think all done - but leave you to confirm and close.

**Comment by rufuspollock** [comment]
FIXED. All working. See `templates/default/layouts`
