### ISSUE TITLE
Review existing Obsidian Publishing options

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#82]
Write up our existing notes on existing Obsidian Publish options (Obsidian Publish and alternatives) so that we are clear for ourselves (and others) why flowershow could be useful to obsidian community

##  Acceptance

* [x] Get list of obsidian publish alternatives (into a note in site)
* [x] Collect following metadata (at least on most interesting ones)
* [x] Review obsidian publish itself
* [x] Brief summary

Metadata

* announce URL ✅
* github URL ✅
* start/announce date ✅
* stars ✅
* is it actively developed ✅
* cost and/or license ✅
* tech approach summary e.g. is it js, what framework, script to static then publish

## Tasks

* [X] Search obsidian forum for announces
* [X] List links for all ones you can find into note doc
* [X] Investigate the most promising / prominent

## Notes

https://forum.obsidian.md/search?q=obsidian%20publish%20alternative

- [ ] Aug 21 list of existing options: https://forum.obsidian.md/t/obsidian-publish-alternatives/22886

**Comment by olayway** [comment]
@rufuspollock  can we close this?

**Comment by rufuspollock** [comment]
FIXED. All done - just need to post up which i will do later.
