### ISSUE TITLE
Use tailwind in (html/jsx) in markdown / mdx files

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#9]
When creating pages for my site I want to (sometimes) use full html with tailwind so i can have fancy layouts or sections

## Acceptance

* [x] can use html with tailwind in my content **✅2022-07-06 you can do this by just adding `content` directory to tailwind which we can do by default now**
* [x] documentation for this **✅2022-07-07 in https://flowershow.app/docs/tailwind**

## Tasks

* [x] Change `tailwind.config.js` to track `content/` folder - see below. **✅2022-07-07 FIXED**
* [ ] ~~Fix the constant hot reloading of pages~~ **✅2022-07-07 WONTFIX as not actually an issue we think - see comments**

## Notes

If we have a setup (as we have) like:

```
tailwind.config.js
content/ <= content is in here
```

should be as simple as tweaking `tailwind.config.js` as follows:

```js
module.exports = {
   content: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}',
       'content/**/*.{md,mdx}'],  // <= added
}
```

This does work ... however it also seems to trigger nextjs into hot reloading the page **all the time** even with no changes. Need to debug and fix this - at least for development mode.

**Comment by olayway** [comment]
@rufuspollock I've tested this and for me, it only seems to recompile when I'm switching pages in obsidian (which doesn't happen when I don't add `/content` folder to taiwlind config). But there is no infinite reload. It only recompiles once - still weird though.
