### ISSUE TITLE
RHS ToC (sidebar current page table of contents)

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#95]
A user can quickly eyeball the contents of the current page by looking at the table of contents (ToC) on the right-hand side. He can also quickly navigate to different sections of the current page by clicking on a section title in the ToC and see where he's currently at thanks to highlighting of the currently focused section.

## Acceptance

- [x] RHS table of contents shows content from current page (excluding the main/page heading??)
- [x] Updates as we scroll the page
- [x] Highlights as we reach different sections
- [x] Questions
  - [x] What happens on non-markdown pages? **Doesn't show**
  - [x] Can we disable toc display? **Yes, in `config.js` or frontmatter see [docs/table-of-contents](https://flowershow.app/docs/table-of-contents) for more info**

## Tasks
- [x] Add ToC Component to layout
- [x] Add `toc` frontmatter field (boolean)
  - [x] set to false on homepage
- [x] Add `tableOfContents` boolean in `config.js`
  - ~~supports all pages (except homepage/non-markdown pages) `tableOfContents: true`~~
  - ~~supports for only specific page/folders on content dir eg. `tableOfContents: ["docs", "about"]`~~
- [x] Add instructions for RHS ToC to docs/table-of-contents

## Screenshot
<img width="1457" alt="Screen Shot 2022-10-18 at 2 47 02 AM" src="https://user-images.githubusercontent.com/42637597/196408927-1c490611-7a81-4cb5-a3c7-5f3d2e13e638.png">

## Notes
Tailwind's solution analysis: https://github.com/datopian/product/blob/main/notes/tailwindcss-website-toc.md

**Comment by olayway** [comment]
@khalilcodes any progress here?

**Comment by khalilcodes** [comment]
@olayway have to fix some eslint errors and will create a PR shortly.

**Comment by rufuspollock** [comment]
@khalilcodes when closing a substantive issue like this can we get a bit more info e.g. a screenshot and/or link to example pages - that is really useful when reviewing the issue.

I also wanted to flag what seems like potentially buggy behaviour on e.g. this page: https://flowershow.app/meta/publishing-design. Here a whole set of headings don't show up in ToC on RHS (my guess is because nested within a h1). Questions:

- I would assume h1 other than very first "title" h1 would show up in ToC (though i'm not totally certain about this or how complex to do0
- even if h1 does not show up i would imagine the h2/h3 etc underneath it would show up ...

![image](https://user-images.githubusercontent.com/180658/199598300-79d48d37-d9e7-4f90-b694-7bb594a7fd19.png)

**Comment by khalilcodes** [comment]
@rufuspollock Thanks for flagging this bug, will look into it.
